(function(g){var window=this;var OHa=function(a,b){return g.Jb(a,b)},v4=function(a,b,c){a.l.set(b,c)},w4=function(a){v4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.C()).toString(36));
return a},x4=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.bn(a.l,b,c)},PHa=function(a,b){var c=[];
g.kj(b,function(d){try{var e=g.Pn.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.On(e)&&c.push(d)},a);
return c},QHa=function(a,b){var c=PHa(a,b);
g.yb(c,function(d){g.Pn.prototype.remove.call(this,d)},a)},RHa=function(a){if(a.W){if(a.W.locationOverrideToken)return{locationOverrideToken:a.W.locationOverrideToken};
if(null!=a.W.latitudeE7&&null!=a.W.longitudeE7)return{latitudeE7:a.W.latitudeE7,longitudeE7:a.W.longitudeE7}}return null},SHa=function(a,b){g.db(a,b)||a.push(b)},y4=function(a){var b=0,c;
for(c in a)b++;return b},THa=function(a,b){var c=b instanceof g.zc?b:g.Fc(b,/^data:image\//i.test(b));
a.src=g.Ac(c)},z4=function(){},UHa=function(a){try{return g.A.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},VHa=function(a){if(a.sg&&"function"==typeof a.sg)return a.sg();
if("string"===typeof a)return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Gb(a)},WHa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||"string"===typeof a)g.yb(a,b,void 0);else{if(a.rh&&"function"==typeof a.rh)var c=a.rh();else if(a.sg&&"function"==typeof a.sg)c=void 0;else if(g.La(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Hb(a);d=VHa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},XHa=function(a,b,c,d){var e=new g.Qm(null,void 0);
a&&g.Rm(e,a);b&&g.Sm(e,b);c&&g.Tm(e,c);d&&(e.J=d);return e},A4=function(a,b){g.Eo[a]=!0;
var c=g.Co();c&&c.publish.apply(c,arguments);g.Eo[a]=!1},B4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Nm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",YHa(this,a.capabilities||""),ZHa(this,a.experiments||""))},YHa=function(a,b){a.capabilities.clear();
g.He(b.split(","),g.Pa(OHa,$Ha)).forEach(function(c){a.capabilities.add(c)})},ZHa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},C4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},D4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},aIa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},bIa=function(a){return new C4(a)},cIa=function(a){return Array.isArray(a)?g.Jc(a,bIa):[]},E4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},F4=function(a){return Array.isArray(a)?"["+g.Jc(a,E4).join(",")+"]":"null"},G4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},dIa=function(a){return g.Jc(a,function(b){return{key:b.id,
name:b.name}})},H4=function(a,b){return g.$a(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},I4=function(a,b){return g.$a(a,function(c){return D4(c,b)})},eIa=function(){var a=(0,g.Cu)();
a&&QHa(a,a.i.Qj(!0))},J4=function(){var a=g.Fu("yt-remote-connected-devices")||[];
g.vb(a);return a},fIa=function(a){if(g.eb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Jc(a,function(d,e){return 0==e?d:d.substring(c.length)})},gIa=function(a){g.Eu("yt-remote-connected-devices",a,86400)},L4=function(){if(K4)return K4;
var a=g.Fu("yt-remote-device-id");a||(a=G4(),g.Eu("yt-remote-device-id",a,31536E3));for(var b=J4(),c=1,d=a;g.db(b,d);)c++,d=a+"#"+c;return K4=d},M4=function(){var a=J4(),b=L4();
g.db(a,b);g.Hu()&&g.xb(a,b);a=fIa(a);if(g.eb(a))try{g.Tq("remote_sid")}catch(c){}else try{g.Rq("remote_sid",a.join(","),-1)}catch(c){}},hIa=function(){return g.Fu("yt-remote-session-browser-channel")},iIa=function(){return g.Fu("yt-remote-local-screens")||[]},jIa=function(){g.Eu("yt-remote-lounge-token-expiration",!0,86400)},kIa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Jc(iIa(),function(d){return d.loungeToken}),c=g.Jc(a,function(d){return d.loungeToken});
g.nh(c,function(d){return!g.db(b,d)})&&jIa();
g.Eu("yt-remote-local-screens",a,31536E3)},lIa=function(a,b){g.Eu("yt-remote-session-browser-channel",a);
g.Eu("yt-remote-session-screen-id",b);var c=J4(),d=L4();g.db(c,d)||c.push(d);gIa(c);M4()},N4=function(a){a||(g.Gu("yt-remote-session-screen-id"),g.Gu("yt-remote-session-video-id"));
M4();a=J4();g.ib(a,L4());gIa(a)},mIa=function(){if(!O4){var a=g.go();
a&&(O4=new g.Jn(a))}},nIa=function(){mIa();
return O4?!!O4.get("yt-remote-use-staging-server"):!1},P4=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},oIa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},pIa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},Q4=function(a){a.length?qIa(a.shift(),function(){Q4(a)}):R4()},rIa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},qIa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.fd(d,g.ng(a));(document.head||document.documentElement).appendChild(d)},sIa=function(){var a=P4(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},R4=function(){var a=pIa();
a&&a(!1,"No cast extension found")},S4=function(){if(tIa){var a=2,b=pIa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;qIa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",R4,c)}},uIa=function(){S4();
var a=sIa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");Q4(a)},wIa=function(){S4();
var a=sIa();a.push.apply(a,g.la(vIa.map(rIa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");Q4(a)},T4=function(a,b,c){g.I.call(this);
this.I=null!=c?(0,g.B)(a,c):a;this.If=b;this.C=(0,g.B)(this.JJ,this);this.i=!1;this.l=0;this.u=this.gb=null;this.B=[]},U4=function(a,b,c){g.I.call(this);
this.B=null!=c?a.bind(c):a;this.If=b;this.u=null;this.i=!1;this.l=0;this.gb=null},V4=function(a){a.gb=g.Lm(function(){a.gb=null;
a.i&&!a.l&&(a.i=!1,V4(a))},a.If);
var b=a.u;a.u=null;a.B.apply(null,b)},W4=function(a){if(g.A.JSON)try{return g.A.JSON.parse(a)}catch(b){}return UHa(a)},X4=function(){},Y4=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.A.setTimeout(function(){a()},b)},$4=function(a){Z4.dispatchEvent(new xIa(Z4,a))},xIa=function(a,b){g.Hl.call(this,"statevent",a);
this.stat=b},a5=function(){},yIa=function(){},AIa=function(a){return(a=zIa(a))?new ActiveXObject(a):new XMLHttpRequest},zIa=function(a){if(!a.l&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},b5=function(a,b,c,d){this.i=a;
this.l=b;this.L=c;this.J=d||1;this.C=45E3;this.B=new g.v_(this);this.u=new g.Km;this.u.setInterval(250)},CIa=function(a,b,c){a.Dp=1;
a.Uk=w4(b.clone());a.zn=c;a.I=!0;BIa(a,null)},c5=function(a,b,c,d,e){a.Dp=1;
a.Uk=w4(b.clone());a.zn=null;a.I=c;e&&(a.JG=!1);BIa(a,d)},BIa=function(a,b){a.rp=g.C();
d5(a);a.Pl=a.Uk.clone();x4(a.Pl,"t",a.J);a.Cs=0;a.De=a.i.vx(a.i.Xr()?b:null);0<a.qw&&(a.Nu=new U4((0,g.B)(a.GH,a,a.De),a.qw));a.B.ya(a.De,"readystatechange",a.aQ);var c=a.jm?g.Qb(a.jm):{};a.zn?(a.Av="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.De.send(a.Pl,a.Av,a.zn,c)):(a.Av="GET",a.JG&&!g.xe&&(c.Connection="close"),a.De.send(a.Pl,a.Av,null,c));a.i.ji(1)},FIa=function(a,b,c){for(var d=!0;!a.Jm&&a.Cs<c.length;){var e=DIa(a,c);
if(e==e5){4==b&&(a.Ok=4,$4(15),d=!1);break}else if(e==EIa){a.Ok=4;$4(16);d=!1;break}else f5(a,e)}4==b&&0==c.length&&(a.Ok=1,$4(17),d=!1);a.zi=a.zi&&d;d||(g5(a),h5(a))},DIa=function(a,b){var c=a.Cs,d=b.indexOf("\n",c);
if(-1==d)return e5;c=Number(b.substring(c,d));if(isNaN(c))return EIa;d+=1;if(d+c>b.length)return e5;var e=b.substr(d,c);a.Cs=d+c;return e},HIa=function(a,b){a.rp=g.C();
d5(a);var c=b?window.location.hostname:"";a.Pl=a.Uk.clone();v4(a.Pl,"DOMAIN",c);v4(a.Pl,"t",a.J);try{a.Di=new ActiveXObject("htmlfile")}catch(n){g5(a);a.Ok=7;$4(22);h5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)h=e+"\\x3c";else if(">"==h)h=e+"\\x3e";else{if(h in i5)h=i5[h];else if(h in GIa)h=i5[h]=GIa[h];else{var l=h.charCodeAt(0);if(31<l&&127>l)var m=h;else{if(256>l){if(m="\\x",16>l||256<l)m+="0"}else m="\\u",4096>l&&(m+="0");m+=l.toString(16).toUpperCase()}h=
i5[h]=m}h=e+h}e=h}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.cd(g.bc("b/12014412"),d+"</body></html>");a.Di.open();a.Di.write(g.Zc(c));a.Di.close();a.Di.parentWindow.m=(0,g.B)(a.uP,a);a.Di.parentWindow.d=(0,g.B)(a.TF,a,!0);a.Di.parentWindow.rpcClose=(0,g.B)(a.TF,a,!1);c=a.Di.createElement("DIV");a.Di.parentWindow.document.body.appendChild(c);d=g.Ec(a.Pl.toString());d=g.kd(g.Ac(d));d=g.cd(g.bc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.dd(c,d);a.i.ji(1)},d5=function(a){a.GA=g.C()+a.C;
IIa(a,a.C)},IIa=function(a,b){if(null!=a.Jp)throw Error("WatchDog timer not null");
a.Jp=Y4((0,g.B)(a.CP,a),b)},j5=function(a){a.Jp&&(g.A.clearTimeout(a.Jp),a.Jp=null)},h5=function(a){a.i.FB()||a.Jm||a.i.Rs(a)},g5=function(a){j5(a);
g.Ni(a.Nu);a.Nu=null;a.u.stop();g.iCa(a.B);if(a.De){var b=a.De;a.De=null;b.abort();b.dispose()}a.Di&&(a.Di=null)},f5=function(a,b){try{a.i.KF(a,b),a.i.ji(4)}catch(c){}},KIa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;JIa(a,b,function(h){h?c(!0):g.A.setTimeout(function(){KIa(a,b,c,d,f)},f)})}},JIa=function(a,b,c){var d=new Image;
d.onload=function(){try{k5(d),c(!0)}catch(e){}};
d.onerror=function(){try{k5(d),c(!1)}catch(e){}};
d.onabort=function(){try{k5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{k5(d),c(!1)}catch(e){}};
g.A.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
THa(d,a)},k5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},l5=function(a){g.am.call(this);
this.headers=new g.Nm;this.ea=a||null;this.B=!1;this.ca=this.i=null;this.za=this.W="";this.I=0;this.u="";this.C=this.la=this.L=this.ga=!1;this.J=0;this.X=null;this.Ca="";this.Y=this.ia=!1},LIa=function(a){return g.ve&&g.Xd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},MIa=function(a){return"content-type"==a.toLowerCase()},OIa=function(a,b){a.B=!1;
a.i&&(a.C=!0,a.i.abort(),a.C=!1);a.u=b;a.I=5;NIa(a);m5(a)},NIa=function(a){a.ga||(a.ga=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},QIa=function(a){if(a.B&&"undefined"!=typeof g.y_)if(a.ca[1]&&4==n5(a)&&2==a.getStatus())o5(a,"Local request error detected and ignored");
else if(a.L&&4==n5(a))g.Lm(a.HF,0,a);else if(a.dispatchEvent("readystatechange"),a.isComplete()){o5(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.td(1,String(a.W));if(!f&&g.A.self&&g.A.self.location){var h=g.A.self.location.protocol;f=h.substr(0,h.length-1)}e=!PIa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.I=6;try{var l=2<n5(a)?a.i.statusText:""}catch(m){l=""}a.u=l+" ["+a.getStatus()+"]";NIa(a)}}finally{m5(a)}}},m5=function(a,b){if(a.i){RIa(a);
var c=a.i,d=a.ca[0]?g.Ia:null;a.i=null;a.ca=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},RIa=function(a){a.i&&a.Y&&(a.i.ontimeout=null);
a.X&&(g.A.clearTimeout(a.X),a.X=null)},n5=function(a){return a.i?a.i.readyState:0},p5=function(a){try{return a.i?a.i.responseText:""}catch(b){return""}},o5=function(a,b){return b+" ["+a.za+" "+a.W+" "+a.getStatus()+"]"},SIa=function(a){this.i=a;
this.l=new X4},TIa=function(a){var b=q5(a.i,a.kq,"/mail/images/cleardot.gif");
w4(b);KIa(b.toString(),5E3,(0,g.B)(a.BK,a),3,2E3);a.ji(1)},s5=function(a){var b=a.i.L;
if(null!=b)$4(5),b?($4(11),r5(a.i,a,!1)):($4(12),r5(a.i,a,!0));else if(a.Cg=new b5(a,void 0,void 0,void 0),a.Cg.jm=a.rw,b=a.i,b=q5(b,b.Xr()?a.aq:null,a.tw),$4(5),!g.ve||g.Yd(10))x4(b,"TYPE","xmlhttp"),c5(a.Cg,b,!1,a.aq,!1);else{x4(b,"TYPE","html");var c=a.Cg;a=!!a.aq;c.Dp=3;c.Uk=w4(b.clone());HIa(c,a)}},t5=function(a,b,c){this.Ma=1;
this.i=[];this.u=[];this.B=new X4;this.J=a||null;this.L=null!=b?b:null;this.C=c||!1},UIa=function(a,b){this.i=a;
this.map=b;this.context=null},VIa=function(a,b,c,d){g.Hl.call(this,"timingevent",a);
this.size=b;this.Qr=d},WIa=function(a){g.Hl.call(this,"serverreachability",a)},ZIa=function(a){XIa(a);
if(3==a.Ma){var b=a.xr++,c=a.wt.clone();v4(c,"SID",a.l);v4(c,"RID",b);v4(c,"TYPE","terminate");u5(a,c);b=new b5(a,a.l,b,void 0);b.Dp=2;b.Uk=w4(c.clone());THa(new Image,b.Uk.toString());b.rp=g.C();d5(b)}YIa(a)},$Ia=function(a){a.VK(1,0);
a.wt=q5(a,null,a.uw);v5(a)},XIa=function(a){a.Yk&&(a.Yk.abort(),a.Yk=null);
a.Zd&&(a.Zd.cancel(),a.Zd=null);a.Rj&&(g.A.clearTimeout(a.Rj),a.Rj=null);w5(a);a.pg&&(a.pg.cancel(),a.pg=null);a.kl&&(g.A.clearTimeout(a.kl),a.kl=null)},aJa=function(a,b){if(0==a.Ma)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new UIa(a.sM++,b));2!=a.Ma&&3!=a.Ma||v5(a)},bJa=function(a){var b=0;
a.Zd&&b++;a.pg&&b++;return b},v5=function(a){a.pg||a.kl||(a.kl=Y4((0,g.B)(a.RF,a),0),a.yo=0)},dJa=function(a,b){if(1==a.Ma){if(!b){a.xr=Math.floor(1E5*Math.random());
var c=a.xr++,d=new b5(a,"",c,void 0);d.jm=a.Ji;var e=x5(a),f=a.wt.clone();v4(f,"RID",c);v4(f,"CVER","1");u5(a,f);CIa(d,f,e);a.pg=d;a.Ma=2}}else 3==a.Ma&&(b?cJa(a,b):0==a.i.length||a.pg||cJa(a))},cJa=function(a,b){if(b)if(6<a.Km){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.xr-1;var d=x5(a)}else c=b.L,d=b.zn;else c=a.xr++,d=x5(a);var e=a.wt.clone();v4(e,"SID",a.l);v4(e,"RID",c);v4(e,"AID",a.So);u5(a,e);c=new b5(a,a.l,c,a.yo+1);c.jm=a.Ji;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.pg=c;CIa(c,e,d)},u5=function(a,b){if(a.yf){var c=a.yf.qD();
c&&g.Ab(c,function(d,e){v4(b,e,d)})}},x5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Km&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Qn:e.Qn},f++){e.Qn=a.i[f].i;var h=a.i[f].map;e.Qn=6>=a.Km?f:e.Qn-d;try{g.Ab(h,function(l){return function(m,n){c.push("req"+l.Qn+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Qn+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},eJa=function(a){a.Zd||a.Rj||(a.I=1,a.Rj=Y4((0,g.B)(a.QF,a),0),a.fo=0)},y5=function(a){if(a.Zd||a.Rj||3<=a.fo)return!1;
a.I++;a.Rj=Y4((0,g.B)(a.QF,a),fJa(a,a.fo));a.fo++;return!0},r5=function(a,b,c){a.yv=c;
a.Ki=b.Oj;a.C||$Ia(a)},w5=function(a){null!=a.Rm&&(g.A.clearTimeout(a.Rm),a.Rm=null)},fJa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},z5=function(a,b){if(2==b||9==b){var c=null;
a.yf&&(c=null);var d=(0,g.B)(a.IQ,a);c||(c=new g.Qm("//www.google.com/images/cleardot.gif"),w4(c));JIa(c.toString(),1E4,d)}else $4(2);gJa(a,b)},gJa=function(a,b){a.Ma=0;
a.yf&&a.yf.GC(b);YIa(a);XIa(a)},YIa=function(a){a.Ma=0;
a.Ki=-1;if(a.yf)if(0==a.u.length&&0==a.i.length)a.yf.ex();else{g.lb(a.u);var b=g.lb(a.i);a.u.length=0;a.i.length=0;a.yf.ex(b)}},q5=function(a,b,c){var d=g.Ym(c);
if(""!=d.i)b&&g.Sm(d,b+"."+d.i),g.Tm(d,d.u);else{var e=window.location;d=XHa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Eq&&g.Ab(a.Eq,function(f,h){v4(d,h,f)});
v4(d,"VER",a.Km);u5(a,d);return d},hJa=function(){},iJa=function(){this.i=[];
this.l=[]},jJa=function(a,b){this.action=a;
this.params=b||{}},A5=function(a,b){g.I.call(this);
this.i=new g.L(this.mP,0,this);g.K(this,this.i);this.If=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.B)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.B)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},B5=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.ca=a;this.I=b;this.u=new g.In;this.l=new A5(this.kQ,this);this.i=null;this.X=!1;this.C=null;this.W="";this.L=this.B=0;this.J=[];this.ea=c;this.Y=d;this.ia=e},kJa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.yv,sessionId:a.i.l,arrayId:a.i.So}},lJa=function(a,b){a.L=b||0;
a.l.stop();C5(a);a.i&&(3==a.i.getState()&&dJa(a.i),ZIa(a.i));a.L=0},D5=function(a){return!!a.i&&3==a.i.getState()},C5=function(a){if(a.i){var b=a.Y(),c=a.i.Ji||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Ji=c}},E5=function(a){this.scheme="https";
this.port=this.domain="";this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.td(4,a))||"";b&&(this.port=":"+b);this.domain=g.ud(a)||"";a=g.Pc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.xc(a,"10.0")&&(this.l=!1))},F5=function(a,b){var c=a.i;
a.l&&(c=a.scheme+"://"+a.domain+a.port+a.i);return g.Id(c+b,{})},G5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Pa(a.B,d,!0),onError:g.Pa(a.u,e),onTimeout:g.Pa(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Yp(b,a)},pJa=function(){var a=mJa;
nJa();H5.push(a);oJa()},I5=function(a,b){nJa();
var c=qJa(a,String(b));g.eb(H5)?rJa(c):(oJa(),g.yb(H5,function(d){d(c)}))},nJa=function(){H5||(H5=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Da("yt.mdx.remote.debug.handlers_",H5,void 0))},rJa=function(a){var b=(J5+1)%50;
J5=b;K5[b]=a;L5||(L5=49==b)},oJa=function(){var a=H5;
if(K5[0]){var b=L5?J5:-1;do{b=(b+1)%50;var c=K5[b];g.yb(a,function(d){d(c)})}while(b!=J5);
K5=Array(50);J5=-1;L5=!1}},qJa=function(a,b){var c=(g.C()-sJa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},M5=function(a){g.Q.call(this);
this.I=a;this.screens=[]},tJa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},uJa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.He(a.screens,function(f){return!!H4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=tJa(a,b[d])||c;return c},vJa=function(a,b){var c=a.screens.length;
a.screens=g.He(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},N5=function(a,b,c,d){g.Q.call(this);
this.u=a;this.I=b;this.B=c;this.C=d;this.l=0;this.i=null;this.gb=NaN},P5=function(a){M5.call(this,"LocalScreenService");
this.l=a;this.i=NaN;O5(this);this.info("Initializing with "+F4(this.screens))},wJa=function(a){if(a.screens.length){var b=g.Jc(a.screens,function(d){return d.id}),c=F5(a.l,"/pairing/get_lounge_token_batch");
G5(a.l,c,{screen_ids:b.join(",")},(0,g.B)(a.wL,a),(0,g.B)(a.vL,a))}},O5=function(a){if(g.Po("deprecate_pair_servlet_enabled"))return uJa(a,[]);
var b=cIa(iIa());b=g.He(b,function(c){return!c.uuid});
return uJa(a,b)},Q5=function(a,b){kIa(g.Jc(a.screens,aIa));
b&&jIa()},S5=function(a,b){g.Q.call(this);
this.I=b;var c=g.Fu("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.I(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.db(c,l)}this.i=d;this.C=a;this.u=this.B=NaN;this.l=null;R5("Initialized with "+g.Oj(this.i))},T5=function(a,b,c){var d=F5(a.C,"/pairing/get_screen_availability");
G5(a.C,d,{lounge_token:b.token},(0,g.B)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.B)(function(){c(!1)},a))},U5=function(a,b){a:if(y4(b)!=y4(a.i))var c=!1;
else{c=g.Hb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(R5("Updated online screens: "+g.Oj(a.i)),a.i=b,a.V("screenChange"));xJa(a)},V5=function(a){isNaN(a.u)||g.Bo(a.u);
a.u=g.zo((0,g.B)(a.Gz,a),0<a.B&&a.B<g.C()?2E4:1E4)},R5=function(a){I5("OnlineScreenService",a)},yJa=function(a){var b={};
g.yb(a.I(),function(c){c.token?b[c.token]=c.id:this.Gd("Requesting availability of screen w/o lounge token.")});
return b},xJa=function(a){a=g.Hb(g.Bb(a.i,function(b){return b}));
g.vb(a);a.length?g.Eu("yt-remote-online-screen-ids",a.join(","),60):g.Gu("yt-remote-online-screen-ids")},W5=function(a){M5.call(this,"ScreenService");
this.B=a;this.i=this.l=null;this.u=[];this.C={};zJa(this)},BJa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.Pg();if(h=(c?I4(h,c):null)||I4(h,b)){h.uuid=b;var l=X5(a,h);T5(a.i,l,function(m){e(m?l:null)})}else c?AJa(a,c,(0,g.B)(function(m){var n=X5(this,new C4({name:d,
screenId:c,loungeToken:m,dialId:b||""}));T5(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},CJa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},DJa=function(a,b,c){T5(a.i,b,c)},AJa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Yp(F5(a.B,"/pairing/get_lounge_token_batch"),e)},EJa=function(a){a.screens=a.l.Pg();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+F4(a.screens))},zJa=function(a){Y5(a);
a.l=new P5(a.B);a.l.subscribe("screenChange",(0,g.B)(a.CL,a));EJa(a);a.u=cIa(g.Fu("yt-remote-automatic-screen-cache")||[]);Y5(a);a.info("Initializing automatic screens: "+F4(a.u));a.i=new S5(a.B,(0,g.B)(a.Pg,a,!0));a.i.subscribe("screenChange",(0,g.B)(function(){this.V("onlineScreenChange")},a))},X5=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=I4(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),FJa(a));Y5(a);a.C[b.uuid]=b.id;g.Eu("yt-remote-device-id-map",a.C,31536E3);return b},FJa=function(a){a=g.He(a.u,function(b){return"shortLived"!=b.idType});
g.Eu("yt-remote-automatic-screen-cache",g.Jc(a,aIa))},Y5=function(a){a.C=g.Fu("yt-remote-device-id-map")||{}},Z5=function(a,b,c){g.Q.call(this);
this.ia=c;this.B=a;this.i=b;this.u=null},$5=function(a,b){a.u=b;
a.V("sessionScreen",a.u)},a6=function(a,b){I5(a.ia,b)},b6=function(a,b,c){Z5.call(this,a,b,"CastSession");
var d=this;this.ga=c;this.l=null;this.Y=(0,g.B)(this.OJ,this);this.ca=(0,g.B)(this.HP,this);this.X=g.zo(function(){GJa(d,null)},12E4);
this.J=this.C=this.I=this.L=0;this.ea=!1;this.W="unknown"},c6=function(a,b){g.Bo(a.J);
a.J=0;0==b?HJa(a):a.J=g.zo(function(){HJa(a)},b)},HJa=function(a){IJa(a,"getLoungeToken");
g.Bo(a.C);a.C=g.zo(function(){JJa(a,null)},3E4)},IJa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Oj(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.B)(function(){a6(this,"Failed to send message: "+b+".")},a)):a6(a,"Sending yt message without session: "+g.Oj(c))},d6=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.HD(b,function(c){$5(a,c)},function(){return a.cg()},5)):a.cg(Error("Waiting for session status timed out."))},LJa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new C4(b);KJa(a,d,function(e){e?(a.ea=!0,X5(a.B,d),$5(a,d),a.W="unknown",c6(a,c)):(g.wo(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.cg())},5)},GJa=function(a,b){g.Bo(a.X);
a.X=0;b?a.ga.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?LJa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.wo(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),d6(a,b.screenId))):(g.wo(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),
d6(a,b.screenId)):d6(a,b.screenId):a.cg(Error("Waiting for session status timed out."))},JJa=function(a,b){g.Bo(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.W=c,c6(a,3E4)):(a.u&&(a.u.token=b.loungeToken,X5(a.B,a.u)),a.V("sessionScreen",a.u),a.ea=!1,a.W="unknown",c6(a,b.loungeTokenRefreshIntervalMs))},KJa=function(a,b,c,d){g.Bo(a.I);
a.I=0;DJa(a.B,b,function(e){e||0>d?c(e):a.I=g.zo(function(){KJa(a,b,c,d-1)},300)})},MJa=function(a){g.Bo(a.L);
a.L=0;g.Bo(a.I);a.I=0;g.Bo(a.X);a.X=0;g.Bo(a.C);a.C=0;g.Bo(a.J);a.J=0},e6=function(a,b,c){Z5.call(this,a,b,"DialSession");
this.C=this.L=null;this.W="";this.ca=c;this.Y=null;this.J=g.Ia;this.I=NaN;this.X=(0,g.B)(this.PJ,this);this.l=g.Ia},NJa=function(a){a.l=a.B.HB(a.W,a.i.label,a.i.friendlyName,(0,g.B)(function(b){this.l=g.Ia;
$5(this,b)},a),(0,g.B)(function(b){this.l=g.Ia;
this.cg(b)},a))},OJa=function(a){var b={};
b.pairingCode=a.W;b.theme=a.ca;nIa()&&(b.env_useStageMdx=1);return g.Gd(b)},f6=function(a,b){Z5.call(this,a,b,"ManualSession");
this.l=g.zo((0,g.B)(this.To,this,null),150)},g6=function(a,b){g.Q.call(this);
this.B=b;this.l=a;this.L=b.appId||"233637DE";this.C=b.theme||"cl";this.W=b.disableCastApi||!1;this.i=null;this.J=!1;this.u=[];this.I=(0,g.B)(this.CO,this)},PJa=function(a,b){return b?g.$a(a.u,function(c){return D4(b,c.label)},a):null},h6=function(a){I5("Controller",a)},mJa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},i6=function(a){return a.J||!!a.u.length||!!a.i},j6=function(a,b,c){b!=a.i&&(g.Ni(a.i),(a.i=b)?(c?a.V("yt-remote-cast2-receiver-resumed",
b.i):a.V("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.B)(a.OF,a,b)),b.getScreen()?a.V("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.To(null)):a.V("yt-remote-cast2-session-change",null))},QJa=function(a){var b=a.l.GB(),c=a.i&&a.i.i;
a=g.Jc(b,function(d){c&&D4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=PJa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},VJa=function(a,b,c,d){d.disableCastApi?k6("Cannot initialize because disabled by Mdx config."):RJa()?SJa(b,d)&&(l6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?TJa(a,c):(window.__onGCastApiAvailable=function(e,f){e?TJa(a,c):(m6("Failed to load cast API: "+f),n6(!1),l6(!1),g.Gu("yt-remote-cast-available"),g.Gu("yt-remote-cast-receiver"),
UJa(),c(!1))},d.loadCastApiSetupScript?g.Lo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=P4()&&uIa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?R4():89<=P4()?wIa():(S4(),Q4(vIa.map(rIa))))):k6("Cannot initialize because not running Chrome")},UJa=function(){k6("dispose");
var a=o6();a&&a.dispose();g.Da("yt.mdx.remote.cloudview.instance_",null,void 0);WJa(!1);g.Ho(p6);p6.length=0},q6=function(){return!!g.Fu("yt-remote-cast-installed")},XJa=function(){var a=g.Fu("yt-remote-cast-receiver");
return a?a.friendlyName:null},YJa=function(){k6("clearCurrentReceiver");
g.Gu("yt-remote-cast-receiver")},ZJa=function(){return q6()?o6()?o6().getCastSession():(m6("getCastSelector: Cast is not initialized."),null):(m6("getCastSelector: Cast API is not installed!"),null)},s6=function(){q6()?o6()?r6()?(k6("Requesting cast selector."),o6().requestSession()):(k6("Wait for cast API to be ready to request the session."),p6.push(g.Go("yt-remote-cast2-api-ready",s6))):m6("requestCastSelector: Cast is not initialized."):m6("requestCastSelector: Cast API is not installed!")},t6=
function(a,b){r6()?o6().setConnectedScreenStatus(a,b):m6("setConnectedScreenStatus called before ready.")},RJa=function(){var a=0<=g.Pc.search(/ (CrMo|Chrome|CriOS)\//);
return g.FA||a},$Ja=function(a,b){o6().init(a,b)},SJa=function(a,b){var c=!1;
o6()||(c=new g6(a,b),c.subscribe("yt-remote-cast2-availability-change",function(d){g.Eu("yt-remote-cast-available",d);A4("yt-remote-cast2-availability-change",d)}),c.subscribe("yt-remote-cast2-receiver-selected",function(d){k6("onReceiverSelected: "+d.friendlyName);
g.Eu("yt-remote-cast-receiver",d);A4("yt-remote-cast2-receiver-selected",d)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(d){k6("onReceiverResumed: "+d.friendlyName);
g.Eu("yt-remote-cast-receiver",d);A4("yt-remote-cast2-receiver-resumed",d)}),c.subscribe("yt-remote-cast2-session-change",function(d){k6("onSessionChange: "+E4(d));
d||g.Gu("yt-remote-cast-receiver");A4("yt-remote-cast2-session-change",d)}),g.Da("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
k6("cloudview.createSingleton_: "+c);return c},o6=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},TJa=function(a,b){n6(!0);
l6(!1);$Ja(a,function(c){c?(WJa(!0),g.Io("yt-remote-cast2-api-ready")):(m6("Failed to initialize cast API."),n6(!1),g.Gu("yt-remote-cast-available"),g.Gu("yt-remote-cast-receiver"),UJa());b(c)})},k6=function(a){I5("cloudview",a)},m6=function(a){I5("cloudview",a)},n6=function(a){k6("setCastInstalled_ "+a);
g.Eu("yt-remote-cast-installed",a)},r6=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},WJa=function(a){k6("setApiReady_ "+a);
g.Da("yt.mdx.remote.cloudview.apiReady_",a,void 0)},l6=function(a){g.Da("yt.mdx.remote.cloudview.initializing_",a,void 0)},u6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.J=this.L=0;this.i=null;this.hasNext=this.cj=!1;this.W=this.I=this.l=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},v6=function(a){a.audioTrackId=null;
a.i=null;a.playerState=-1;a.cj=!1;a.hasNext=!1;a.L=0;a.J=g.C();a.C=0;a.l=0;a.I=0;a.W=0;a.B=NaN;a.u=!1},w6=function(a){return a.Kb()?(g.C()-a.J)/1E3:0},x6=function(a,b){a.L=b;
a.J=g.C()},y6=function(a){switch(a.playerState){case 1:case 1081:return(g.C()-a.J)/1E3+a.L;
case -1E3:return 0}return a.L},z6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&v6(a)},A6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Rb(a.i);b.hasPrevious=a.cj;b.hasNext=a.hasNext;b.playerTime=a.L;b.playerTimeAt=a.J;b.seekableStart=a.C;b.seekableEnd=a.l;b.duration=a.I;b.loadedTime=a.W;b.liveIngestionTime=a.B;return b},C6=function(a,b){g.Q.call(this);
this.Ma=0;this.u=a;this.C=[];this.B=new iJa;this.l=this.i=null;this.L=(0,g.B)(this.eN,this);this.I=(0,g.B)(this.zr,this);this.J=(0,g.B)(this.dN,this);this.W=(0,g.B)(this.lN,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Uz,this),aKa(this))):c=3;0!=c&&(b?this.Uz(c):g.zo((0,g.B)(function(){this.Uz(c)},this),0));
var d=ZJa();d&&B6(this,d);this.subscribe("yt-remote-cast2-session-change",this.W)},D6=function(a){return new u6(a.u.getPlayerContextData())},aKa=function(a){g.yb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Pa(this.zO,b),this))},a)},bKa=function(a){g.yb(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},E6=function(a){return 1==a.getState()},F6=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},H6=function(a,b,c){var d=D6(a);
x6(d,c);-1E3!=d.playerState&&(d.playerState=b);G6(a,d)},I6=function(a,b,c){a.u.sendMessage(b,c)},G6=function(a,b){bKa(a);
a.u.setPlayerContextData(A6(b));aKa(a)},B6=function(a,b){a.l&&(a.l.removeUpdateListener(a.L),a.l.removeMediaListener(a.I),a.zr(null));
a.l=b;a.l&&(I5("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.L),a.l.addMediaListener(a.I),a.l.media.length&&a.zr(a.l.media[0]))},cKa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=D6(a);b.contentId!=d.videoId&&I5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;x6(d,a.i.getEstimatedTime());G6(a,d)}else I5("CP","No cast media video. Ignoring state update.")},J6=function(a,b,c){return(0,g.B)(function(d){this.Gd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Gd("Retrying "+b+" using MDx browser channel."),I6(this,b,c))},a)},K6=function(a,b,c){g.Q.call(this);
this.C=NaN;this.ca=!1;this.L=this.J=this.X=this.Y=NaN;this.W=[];this.B=this.I=this.u=this.Fb=this.i=null;this.ia=a;this.W.push(g.ap(window,"beforeunload",(0,g.B)(this.qL,this)));this.l=[];this.Fb=new u6;this.ga=b.id;this.ea=b.idType;this.i=dKa(this,c);this.i.subscribe("handlerOpened",this.iN,this);this.i.subscribe("handlerClosed",this.fN,this);this.i.subscribe("handlerError",this.gN,this);this.i.subscribe("handlerMessage",this.hN,this);this.i.Xu(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.Fb.videoId;g.Hu()&&g.Eu("yt-remote-session-video-id",d)},this)},L6=function(a){I5("conn",a)},dKa=function(a,b){return new B5(F5(a.ia,"/bc"),b,!1,function(){return a.LB()},"shortLived"==a.ea)},M6=function(a,b){a.V("proxyStateChange",b)},eKa=function(a){a.C=g.zo((0,g.B)(function(){L6("Connecting timeout");
this.uo(1)},a),2E4)},N6=function(a){g.Bo(a.C);
a.C=NaN},O6=function(a){g.Bo(a.Y);
a.Y=NaN},fKa=function(a){P6(a);
a.X=g.zo((0,g.B)(function(){Q6(this,"getNowPlaying")},a),2E4)},P6=function(a){g.Bo(a.X);
a.X=NaN},hKa=function(a,b){b&&(N6(a),O6(a));
var c=D5(a.i)&&isNaN(a.C);b==c?b&&(M6(a,1),Q6(a,"getSubtitlesTrack")):b?(a.GD()&&a.Fb.reset(),M6(a,1),Q6(a,"getNowPlaying"),gKa(a)):a.uo(1)},iKa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Fb.videoId&&(g.Mb(b.params)?a.Fb.i=null:a.Fb.i=b.params,a.V("remotePlayerChange"))},jKa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Fb.listId=b.params.listId||a.Fb.listId;z6(a.Fb,c,d);a.V("remoteQueueChange")},lKa=function(a,b){b.params=b.params||{};
jKa(a,b);kKa(a,b);a.V("autoplayDismissed")},kKa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
x6(a.Fb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Fb.playerState&&(c=-1E3);a.Fb.playerState=c;c=Number(b.params.loadedTime);a.Fb.W=isNaN(c)?0:c;c=Number(b.params.duration);a.Fb.I=isNaN(c)?0:c;c=a.Fb;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.Fb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.l=isNaN(e)?0:e;1==a.Fb.playerState?fKa(a):P6(a);a.V("remotePlayerChange")},mKa=function(a,b){if(-1E3!=
a.Fb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Fb.playerState=c;c=parseInt(b.params.currentTime,10);x6(a.Fb,isNaN(c)?0:c);a.V("remotePlayerChange")}},nKa=function(a,b){var c="true"==b.params.muted;
a.Fb.volume=parseInt(b.params.volume,10);a.Fb.muted=c;a.V("remotePlayerChange")},oKa=function(a,b){a.I=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},pKa=function(a,b){var c="true"==b.params.hasNext;
a.Fb.cj="true"==b.params.hasPrevious;a.Fb.hasNext=c;a.V("previousNextChange")},gKa=function(a){g.Bo(a.L);
a.L=g.zo((0,g.B)(a.uo,a,1),864E5)},Q6=function(a,b,c){c?L6("Sending: action="+b+", params="+g.Oj(c)):L6("Sending: action="+b);
a.i.sendMessage(b,c)},R6=function(a){M5.call(this,"ScreenServiceProxy");
this.Hf=a;this.i=[];this.i.push(this.Hf.$_s("screenChange",(0,g.B)(this.TJ,this)));this.i.push(this.Hf.$_s("onlineScreenChange",(0,g.B)(this.gO,this)))},tKa=function(a,b){mIa();
if(!O4||!O4.get("yt-remote-disable-remote-module-for-dev")){b=g.O("MDX_CONFIG")||b;eIa();M4();S6||(S6=new E5(b?b.loungeApiHost:void 0),nIa()&&(S6.i="/api/loungedev"));T6||(T6=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Da("yt.mdx.remote.deferredProxies_",T6,void 0));qKa();var c=U6();if(!c){var d=new W5(S6);g.Da("yt.mdx.remote.screenService_",d,void 0);c=U6();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,disableCastApi:b.disableCastApi,
enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});VJa(a,d,function(h){h?V6()&&t6(V6(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){A4("yt-remote-receiver-availability-change")})},e)}if(b&&!g.Ha("yt.mdx.remote.initialized_")){g.Da("yt.mdx.remote.initialized_",!0,void 0);
W6("Initializing: "+g.Oj(b));X6.push(g.Go("yt-remote-cast2-availability-change",function(){A4("yt-remote-receiver-availability-change")}));
X6.push(g.Go("yt-remote-cast2-receiver-selected",function(){Y6(null);A4("yt-remote-auto-connect","cast-selector-receiver")}));
X6.push(g.Go("yt-remote-cast2-receiver-resumed",function(){A4("yt-remote-receiver-resumed","cast-selector-receiver")}));
X6.push(g.Go("yt-remote-cast2-session-change",rKa));X6.push(g.Go("yt-remote-connection-change",function(h){h?t6(V6(),"YouTube TV"):Z6()||(t6(null,null),YJa())}));
e=$6();b.isAuto&&(e.id+="#dial");g.Po("desktop_enable_autoplay")&&(e.capabilities=["atp"]);e.name=b.device;e.app=b.app;var f=b.theme;f&&(e.theme=f);W6(" -- with channel params: "+g.Oj(e));e?(g.Eu("yt-remote-session-app",e.app),g.Eu("yt-remote-session-name",e.name)):(g.Gu("yt-remote-session-app"),g.Gu("yt-remote-session-name"));g.Da("yt.mdx.remote.channelParams_",e,void 0);c.start();V6()||sKa()}}},uKa=function(){var a=U6().Hf.$_gos();
var b=a7();b&&b7()&&(H4(a,b)||a.push(b));return dIa(a)},c7=function(){var a=vKa();
!a&&q6()&&XJa()&&(a={key:"cast-selector-receiver",name:XJa()});return a},vKa=function(){var a=uKa(),b=a7();
b||(b=Z6());return g.$a(a,function(c){return b&&D4(b,c.key)?!0:!1})},a7=function(){var a=V6();
if(!a)return null;var b=U6().Pg();return I4(b,a)},rKa=function(a){W6("remote.onCastSessionChange_: "+E4(a));
if(a){var b=a7();if(b&&b.id==a.id){if(t6(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))d7&&(d7.token=a),(b=b7())&&b.Xu(a)}else b&&e7(),f7(a,1)}else b7()&&e7()},e7=function(){r6()?o6().stopSession():m6("stopSession called before API ready.");
var a=b7();a&&(a.disconnect(1),g7(null))},h7=function(){var a=b7();
return!!a&&3!=a.getProxyState()},W6=function(a){I5("remote",a)},U6=function(){if(!i7){var a=g.Ha("yt.mdx.remote.screenService_");
i7=a?new R6(a):null}return i7},V6=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},wKa=function(a){g.Da("yt.mdx.remote.currentScreenId_",a,void 0)},xKa=function(){return g.Ha("yt.mdx.remote.connectData_")},Y6=function(a){g.Da("yt.mdx.remote.connectData_",a,void 0)},b7=function(){return g.Ha("yt.mdx.remote.connection_")},g7=function(a){var b=b7();
Y6(null);a||wKa("");g.Da("yt.mdx.remote.connection_",a,void 0);T6&&(g.yb(T6,function(c){c(a)}),T6.length=0);
b&&!a?A4("yt-remote-connection-change",!1):!b&&a&&A4("yt-remote-connection-change",!0)},Z6=function(){var a=g.Hu();
if(!a)return null;var b=U6();if(!b)return null;b=b.Pg();return I4(b,a)},f7=function(a,b){V6();
a7()&&a7();if(j7)d7=a;else{wKa(a.id);var c=new K6(S6,a,$6());c.connect(b,xKa());c.subscribe("beforeDisconnect",function(d){A4("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){b7()&&(b7(),g7(null))});
c.subscribe("browserChannelAuthError",function(){var d=a7();d&&"shortLived"==d.idType&&(r6()?o6().handleBrowserChannelAuthError():m6("refreshLoungeToken called before API ready."))});
g7(c)}},sKa=function(){var a=Z6();
a?(W6("Resume connection to: "+E4(a)),f7(a,0)):(N4(),YJa(),W6("Skipping connecting because no session screen found."))},qKa=function(){var a=$6();
if(g.Mb(a)){a=L4();var b=g.Fu("yt-remote-session-name")||"",c=g.Fu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Da("yt.mdx.remote.channelParams_",a,void 0)}},$6=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},k7=function(a,b,c){g.I.call(this);
var d=this;this.l=a;this.G=b;this.wb=c;this.events=new g.yN(this);this.X=this.events.N(this.G,"onVolumeChange",function(e){yKa(d,e)});
this.C=!1;this.suggestion=null;this.I=new g.uK(64);this.i=new g.L(this.TG,500,this);this.u=new g.L(this.UG,1E3,this);this.L=new T4(this.ZQ,0,this);this.B={};this.W=new g.L(this.wH,1E3,this);this.J=new U4(this.seekTo,1E3,this);this.Y=g.Ia;g.K(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.PN);this.events.N(b,"captionschanged",this.bN);this.events.N(b,"captionssettingschanged",this.ZG);this.events.N(b,"videoplayerreset",this.Gu);this.events.N(b,"mdxautoplaycancel",function(){d.wb.aD()});
a=this.wb;a.na();a.subscribe("proxyStateChange",this.JF,this);a.subscribe("remotePlayerChange",this.Fr,this);a.subscribe("remoteQueueChange",this.Gu,this);a.subscribe("previousNextChange",this.GF,this);a.subscribe("nowAutoplaying",this.BF,this);a.subscribe("autoplayDismissed",this.bF,this);g.K(this,this.i);g.K(this,this.u);g.K(this,this.L);g.K(this,this.W);g.K(this,this.J);this.ZG();this.Gu();this.Fr()},yKa=function(a,b){if(l7(a)){a.wb.unsubscribe("remotePlayerChange",a.Fr,a);
var c=Math.round(b.volume),d=!!b.muted,e=D6(a.wb);if(c!==e.volume||d!==e.muted)a.wb.setVolume(c,d),a.W.start();a.wb.subscribe("remotePlayerChange",a.Fr,a)}},zKa=function(a){a.Bb(0);
a.i.stop();a.tb(new g.uK(64))},m7=function(a,b){if(l7(a)&&!a.C){var c=null;
b&&(c={style:a.G.getSubtitlesUserSettings()},g.Tb(c,b));a.wb.KB(a.G.getVideoData(1).videoId,c);a.B=D6(a.wb).i}},n7=function(a,b){var c=a.G.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.G.getVideoData(1);a.wb.playVideo(c.videoId,b,d,e,c.playerParams,c.ia,RHa(c));a.tb(new g.uK(1))},AKa=function(a,b){if(b){var c=a.G.getOption("captions","tracklist",{aE:1});
c&&c.length?(a.G.setOption("captions","track",b),a.C=!1):(a.G.loadModule("captions"),a.C=!0)}else a.G.setOption("captions","track",{})},l7=function(a){return D6(a.wb).videoId===a.G.getVideoData(1).videoId},o7=function(){g.W.call(this,{D:"div",
K:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-title",ba:"Connecting to your TV on web using a code will be going away soon"},{D:"div",K:"ytp-mdx-manual-pairing-popup-buttons",S:[{D:"button",ka:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],ba:"Learn more"},{D:"button",ka:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],ba:"OK"}]}]}]});this.i=new g.dM(this,250);this.learnMoreButton=
this.ha("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ha("ytp-mdx-manual-pairing-popup-ok");g.K(this,this.i);this.N(this.learnMoreButton,"click",this.l);this.N(this.okButton,"click",this.u)},p7=function(){g.W.call(this,{D:"div",
K:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-popup-title",ba:"You're signed out"},{D:"div",K:"ytp-mdx-popup-description",ba:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",K:"ytp-mdx-privacy-popup-buttons",S:[{D:"button",ka:["ytp-button","ytp-mdx-privacy-popup-cancel"],ba:"Cancel"},{D:"button",ka:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],ba:"Confirm"}]}]}]});this.i=new g.dM(this,250);this.cancelButton=this.ha("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ha("ytp-mdx-privacy-popup-confirm");g.K(this,this.i);this.N(this.cancelButton,"click",this.l);this.N(this.confirmButton,"click",this.u)},q7=function(a){g.W.call(this,{D:"div",
K:"ytp-remote",S:[{D:"div",K:"ytp-remote-display-status",S:[{D:"div",K:"ytp-remote-display-status-icon",S:[g.Jma()]},{D:"div",K:"ytp-remote-display-status-text",ba:"{{statustext}}"}]}]});this.api=a;this.i=new g.dM(this,250);g.K(this,this.i);this.N(a,"presentingplayerstatechange",this.l);BKa(this,a.Va())},BKa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.V(b,128)?g.TJ("Error on $RECEIVER_NAME",c):b.Kb()||g.V(b,4)?g.TJ("Playing on $RECEIVER_NAME",c):g.TJ("Connected to $RECEIVER_NAME",c);a.Aa("statustext",c);a.i.show()}else a.i.hide()},r7=function(a,b){g.SQ.call(this,"Play on",0,a,b);
this.G=a;this.Ml={};this.N(a,"onMdxReceiversChange",this.C);this.N(a,"presentingplayerstatechange",this.C);this.C()},s7=function(a){g.GN.call(this,a);
this.gi={key:G4(),name:"This computer"};this.lh=null;this.subscriptions=[];this.vz=this.wb=null;this.Ml=[this.gi];this.al=this.gi;this.Mc=new g.uK(64);this.vE=0;this.Ne=-1;this.Xo=null;this.Ir=this.lu=!1;this.yn=this.pp=null;if(!g.VC(this.player.T())){a=this.player;var b=g.mN(a);b&&(b=b.an())&&(b=new r7(a,b),g.K(this,b));b=new q7(a);g.K(this,b);g.wN(a,b.element,4);this.pp=new p7;g.K(this,this.pp);g.wN(a,this.pp.element,4);g.S(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.S(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.Xo=new o7,g.K(this,this.Xo),g.wN(a,this.Xo.element,4));this.Ir=!!Z6();this.lu=!!g.Fu("yt-remote-manual-pairing-warning-shown")}},t7=function(a){a.yn&&(a.player.removeEventListener("presentingplayerstatechange",a.yn),a.yn=null)},CKa=function(a,b,c){a.Mc=c;
a.player.V("presentingplayerstatechange",new g.zJ(c,b))},DKa=function(a,b,c){var d=!1;
1===b?d=!a.Ir:2===b&&(d=!a.lu);d&&g.BJ(c,8)&&(a.player.pauseVideo(),t7(a))},u7=function(a,b){if(b.key!==a.al.key)if(b.key===a.gi.key)e7();
else{if(a.Xo&&!a.lu&&b!==a.gi&&"cast-selector-receiver"!==b.key&&g.oD(a.player.T()))EKa(a);else{var c;(c=!g.S(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.O("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.O("SESSION_INDEX")&&!g.O("LOGGED_IN")))||a.Ir||!a.pp);(c?0:g.oD(a.player.T())||g.sD(a.player.T()))&&FKa(a)}a.al=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.S(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.Na(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.ia,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=RHa(c))&&(d.locationInfo=c);c=d}W6("Connecting to: "+g.Oj(b));"cast-selector-receiver"==b.key?(Y6(c||null),c=c||null,
r6()?o6().setLaunchParams(c):m6("setLaunchParams called before ready.")):!c&&h7()&&V6()==b.key?A4("yt-remote-connection-change",!0):(e7(),Y6(c||null),c=U6().Pg(),(c=I4(c,b.key))&&f7(c,1))}},FKa=function(a){a.player.Va().Kb()?a.player.pauseVideo():(a.yn=function(b){DKa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.yn));
a.pp&&a.pp.Ec();b7()||(j7=!0)},EKa=function(a){a.player.Va().Kb()?a.player.pauseVideo():(a.yn=function(b){DKa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.yn));
a.Xo&&a.Xo.Ec();b7()||(j7=!0)},GIa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},i5={"'":"\\'"},GKa={},$Ha={WR:"atp",o1:"ska",n0:"que",vZ:"mus",n1:"sus",NV:"dsp",F0:"seq",ZY:"mic",NU:"dpa"},O4,K4="",tIa=oIa("loadCastFramework")||oIa("loadCastApplicationFramework"),vIa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ra(T4,g.I);g.k=T4.prototype;g.k.Og=function(a){this.B=arguments;this.i=!1;this.gb?this.u=g.C()+this.If:this.gb=g.Lm(this.C,this.If)};
g.k.stop=function(){this.gb&&(g.A.clearTimeout(this.gb),this.gb=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.I.apply(null,this.B)))};
g.k.da=function(){this.stop();T4.Ed.da.call(this)};
g.k.JJ=function(){this.u?(this.gb=g.Lm(this.C,this.u-g.C()),this.u=null):(this.gb=null,this.l?this.i=!0:(this.i=!1,this.I.apply(null,this.B)))};g.u(U4,g.I);g.k=U4.prototype;g.k.Og=function(a){this.u=arguments;this.gb||this.l?this.i=!0:V4(this)};
g.k.stop=function(){this.gb&&(g.A.clearTimeout(this.gb),this.gb=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.gb||(this.i=!1,V4(this))};
g.k.da=function(){g.I.prototype.da.call(this);this.stop()};X4.prototype.stringify=function(a){return g.A.JSON.stringify(a,void 0)};
X4.prototype.parse=function(a){return g.A.JSON.parse(a,void 0)};var Z4=new g.am;g.u(xIa,g.Hl);a5.prototype.i=null;a5.prototype.getOptions=function(){var a;(a=this.i)||(a={},zIa(this)&&(a[0]=!0,a[1]=!0),a=this.i=a);return a};var v7;g.Ra(yIa,a5);v7=new yIa;g.k=b5.prototype;g.k.jm=null;g.k.zi=!1;g.k.Jp=null;g.k.GA=null;g.k.rp=null;g.k.Dp=null;g.k.Uk=null;g.k.Pl=null;g.k.zn=null;g.k.De=null;g.k.Cs=0;g.k.Di=null;g.k.Av=null;g.k.Ok=null;g.k.Zp=-1;g.k.JG=!0;g.k.Jm=!1;g.k.qw=0;g.k.Nu=null;var EIa={},e5={};g.k=b5.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.aQ=function(a){a=a.target;var b=this.Nu;b&&3==n5(a)?b.Og():this.GH(a)};
g.k.GH=function(a){try{if(a==this.De)a:{var b=n5(this.De),c=this.De.I,d=this.De.getStatus();if(g.ve&&!g.Yd(10)||g.xe&&!g.Xd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.ug&&!p5(this.De))break a;this.Jm||4!=b||7==c||(8==c||0>=d?this.i.ji(3):this.i.ji(2));j5(this);var e=this.De.getStatus();this.Zp=e;var f=p5(this.De);(this.zi=200==e)?(4==b&&g5(this),this.I?(FIa(this,b,f),g.ug&&this.zi&&3==b&&(this.B.ya(this.u,"tick",this.TP),this.u.start())):f5(this,f),this.zi&&!this.Jm&&(4==b?this.i.Rs(this):(this.zi=
!1,d5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Ok=3,$4(13)):(this.Ok=0,$4(14)),g5(this),h5(this))}}catch(h){this.De&&p5(this.De)}finally{}};
g.k.TP=function(){var a=n5(this.De),b=p5(this.De);this.Cs<b.length&&(j5(this),FIa(this,a,b),this.zi&&4!=a&&d5(this))};
g.k.uP=function(a){Y4((0,g.B)(this.tP,this,a),0)};
g.k.tP=function(a){this.Jm||(j5(this),f5(this,a),d5(this))};
g.k.TF=function(a){Y4((0,g.B)(this.sP,this,a),0)};
g.k.sP=function(a){this.Jm||(g5(this),this.zi=a,this.i.Rs(this),this.i.ji(4))};
g.k.cancel=function(){this.Jm=!0;g5(this)};
g.k.CP=function(){this.Jp=null;var a=g.C();0<=a-this.GA?(2!=this.Dp&&this.i.ji(3),g5(this),this.Ok=2,$4(18),h5(this)):IIa(this,this.GA-a)};
g.k.getLastError=function(){return this.Ok};g.Ra(l5,g.am);var PIa=/^https?$/i,HKa=["POST","PUT"];g.k=l5.prototype;
g.k.send=function(a,b,c,d){if(this.i)throw Error("[goog.net.XhrIo] Object is active with another request="+this.W+"; newUri="+a);b=b?b.toUpperCase():"GET";this.W=a;this.u="";this.I=0;this.za=b;this.ga=!1;this.B=!0;this.i=this.ea?AIa(this.ea):AIa(v7);this.ca=this.ea?this.ea.getOptions():v7.getOptions();this.i.onreadystatechange=(0,g.B)(this.HF,this);try{z4(o5(this,"Opening Xhr")),this.la=!0,this.i.open(b,String(a),!0),this.la=!1}catch(f){z4(o5(this,"Error opening Xhr: "+f.message));OIa(this,f);return}a=
c||"";var e=this.headers.clone();d&&WHa(d,function(f,h){e.set(h,f)});
d=g.$a(e.rh(),MIa);c=g.A.FormData&&a instanceof g.A.FormData;!g.db(HKa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.i.setRequestHeader(h,f)},this);
this.Ca&&(this.i.responseType=this.Ca);"withCredentials"in this.i&&this.i.withCredentials!==this.ia&&(this.i.withCredentials=this.ia);try{RIa(this),0<this.J&&(this.Y=LIa(this.i),z4(o5(this,"Will abort after "+this.J+"ms if incomplete, xhr2 "+this.Y)),this.Y?(this.i.timeout=this.J,this.i.ontimeout=(0,g.B)(this.EB,this)):this.X=g.Lm(this.EB,this.J,this)),z4(o5(this,"Sending request")),this.L=!0,this.i.send(a),this.L=!1}catch(f){z4(o5(this,"Send error: "+f.message)),OIa(this,f)}};
g.k.EB=function(){"undefined"!=typeof g.y_&&this.i&&(this.u="Timed out after "+this.J+"ms, aborting",this.I=8,o5(this,this.u),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.i&&this.B&&(o5(this,"Aborting"),this.B=!1,this.C=!0,this.i.abort(),this.C=!1,this.I=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),m5(this))};
g.k.da=function(){this.i&&(this.B&&(this.B=!1,this.C=!0,this.i.abort(),this.C=!1),m5(this,!0));l5.Ed.da.call(this)};
g.k.HF=function(){this.na()||(this.la||this.L||this.C?QIa(this):this.BO())};
g.k.BO=function(){QIa(this)};
g.k.isActive=function(){return!!this.i};
g.k.isComplete=function(){return 4==n5(this)};
g.k.getStatus=function(){try{return 2<n5(this)?this.i.status:-1}catch(a){return-1}};
g.k.getResponseHeader=function(a){if(this.i&&this.isComplete())return a=this.i.getResponseHeader(a),null===a?void 0:a};
g.k.getLastError=function(){return"string"===typeof this.u?this.u:String(this.u)};g.k=SIa.prototype;g.k.rw=null;g.k.Cg=null;g.k.Ou=!1;g.k.VG=null;g.k.vt=null;g.k.Ny=null;g.k.tw=null;g.k.Ma=null;g.k.Oj=-1;g.k.aq=null;g.k.kq=null;g.k.connect=function(a){this.tw=a;a=q5(this.i,null,this.tw);$4(3);this.VG=g.C();var b=this.i.J;null!=b?(this.aq=b[0],(this.kq=b[1])?(this.Ma=1,TIa(this)):(this.Ma=2,s5(this))):(x4(a,"MODE","init"),this.Cg=new b5(this,void 0,void 0,void 0),this.Cg.jm=this.rw,c5(this.Cg,a,!1,null,!0),this.Ma=0)};
g.k.BK=function(a){if(a)this.Ma=2,s5(this);else{$4(4);var b=this.i;b.Ki=b.Yk.Oj;z5(b,9)}a&&this.ji(2)};
g.k.vx=function(a){return this.i.vx(a)};
g.k.abort=function(){this.Cg&&(this.Cg.cancel(),this.Cg=null);this.Oj=-1};
g.k.FB=function(){return!1};
g.k.KF=function(a,b){this.Oj=a.Zp;if(0==this.Ma)if(b){try{var c=this.l.parse(b)}catch(d){c=this.i;c.Ki=this.Oj;z5(c,2);return}this.aq=c[0];this.kq=c[1]}else c=this.i,c.Ki=this.Oj,z5(c,2);else if(2==this.Ma)if(this.Ou)$4(7),this.Ny=g.C();else if("11111"==b){if($4(6),this.Ou=!0,this.vt=g.C(),c=this.vt-this.VG,!g.ve||g.Yd(10)||500>c)this.Oj=200,this.Cg.cancel(),$4(12),r5(this.i,this,!0)}else $4(8),this.vt=this.Ny=g.C(),this.Ou=!1};
g.k.Rs=function(){this.Oj=this.Cg.Zp;if(this.Cg.zi)0==this.Ma?this.kq?(this.Ma=1,TIa(this)):(this.Ma=2,s5(this)):2==this.Ma&&((!g.ve||g.Yd(10)?!this.Ou:200>this.Ny-this.vt)?($4(11),r5(this.i,this,!1)):($4(12),r5(this.i,this,!0)));else{0==this.Ma?$4(9):2==this.Ma&&$4(10);var a=this.i;this.Cg.getLastError();a.Ki=this.Oj;z5(a,2)}};
g.k.Xr=function(){return this.i.Xr()};
g.k.isActive=function(){return this.i.isActive()};
g.k.ji=function(a){this.i.ji(a)};g.k=t5.prototype;g.k.Ji=null;g.k.Eq=null;g.k.pg=null;g.k.Zd=null;g.k.uw=null;g.k.wt=null;g.k.tC=null;g.k.Ss=null;g.k.xr=0;g.k.sM=0;g.k.yf=null;g.k.kl=null;g.k.Rj=null;g.k.Rm=null;g.k.Yk=null;g.k.yv=null;g.k.So=-1;g.k.uE=-1;g.k.Ki=-1;g.k.yo=0;g.k.fo=0;g.k.Km=8;g.Ra(VIa,g.Hl);g.Ra(WIa,g.Hl);g.k=t5.prototype;g.k.connect=function(a,b,c,d,e){$4(0);this.uw=b;this.Eq=c||{};d&&void 0!==e&&(this.Eq.OSID=d,this.Eq.OAID=e);this.C?(Y4((0,g.B)(this.MC,this,a),100),$Ia(this)):this.MC(a)};
g.k.MC=function(a){this.Yk=new SIa(this);this.Yk.rw=this.Ji;this.Yk.l=this.B;this.Yk.connect(a)};
g.k.FB=function(){return 0==this.Ma};
g.k.getState=function(){return this.Ma};
g.k.RF=function(a){this.kl=null;dJa(this,a)};
g.k.QF=function(){this.Rj=null;this.Zd=new b5(this,this.l,"rpc",this.I);this.Zd.jm=this.Ji;this.Zd.qw=0;var a=this.tC.clone();v4(a,"RID","rpc");v4(a,"SID",this.l);v4(a,"CI",this.yv?"0":"1");v4(a,"AID",this.So);u5(this,a);if(!g.ve||g.Yd(10))v4(a,"TYPE","xmlhttp"),c5(this.Zd,a,!0,this.Ss,!1);else{v4(a,"TYPE","html");var b=this.Zd,c=!!this.Ss;b.Dp=3;b.Uk=w4(a.clone());HIa(b,c)}};
g.k.KF=function(a,b){if(0!=this.Ma&&(this.Zd==a||this.pg==a))if(this.Ki=a.Zp,this.pg==a&&3==this.Ma)if(7<this.Km){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Rj){if(this.Zd)if(this.Zd.rp+3E3<this.pg.rp)w5(this),this.Zd.cancel(),this.Zd=null;else break a;y5(this);$4(19)}}else this.uE=c[1],0<this.uE-this.So&&37500>c[2]&&this.yv&&0==this.fo&&!this.Rm&&(this.Rm=Y4((0,g.B)(this.XM,this),6E3));else z5(this,11)}else b!=GKa.BU.i&&z5(this,11);else if(this.Zd==
a&&w5(this),!g.mc(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.So=e[0];e=e[1];2==this.Ma?"c"==e[0]?(this.l=e[1],this.Ss=e[2],e=e[3],null!=e?this.Km=e:this.Km=6,this.Ma=3,this.yf&&this.yf.IC(),this.tC=q5(this,this.Xr()?this.Ss:null,this.uw),eJa(this)):"stop"==e[0]&&z5(this,7):3==this.Ma&&("stop"==e[0]?z5(this,7):"noop"!=e[0]&&this.yf&&this.yf.HC(e),this.fo=0)}}};
g.k.XM=function(){null!=this.Rm&&(this.Rm=null,this.Zd.cancel(),this.Zd=null,y5(this),$4(20))};
g.k.Rs=function(a){if(this.Zd==a){w5(this);this.Zd=null;var b=2}else if(this.pg==a)this.pg=null,b=1;else return;this.Ki=a.Zp;if(0!=this.Ma)if(a.zi)1==b?(b=Z4,b.dispatchEvent(new VIa(b,a.zn?a.zn.length:0,g.C()-a.rp,this.yo)),v5(this),this.u.length=0):eJa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ki)){if(d=1==b)this.pg||this.kl||1==this.Ma||2<=this.yo?d=!1:(this.kl=Y4((0,g.B)(this.RF,this,a),fJa(this,this.yo)),this.yo++,d=!0);d=!(d||2==b&&y5(this))}if(d)switch(c){case 1:z5(this,
5);break;case 4:z5(this,10);break;case 3:z5(this,6);break;case 7:z5(this,12);break;default:z5(this,2)}}};
g.k.VK=function(a){if(!g.db(arguments,this.Ma))throw Error("Unexpected channel state: "+this.Ma);};
g.k.IQ=function(a){a?$4(2):($4(1),gJa(this,8))};
g.k.vx=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new l5;a.ia=!1;return a};
g.k.isActive=function(){return!!this.yf&&this.yf.isActive(this)};
g.k.ji=function(a){var b=Z4;b.dispatchEvent(new WIa(b,a))};
g.k.Xr=function(){return!(!g.ve||g.Yd(10))};
g.k=hJa.prototype;g.k.IC=function(){};
g.k.HC=function(){};
g.k.GC=function(){};
g.k.ex=function(){};
g.k.qD=function(){return{}};
g.k.isActive=function(){return!0};g.k=iJa.prototype;g.k.isEmpty=function(){return g.eb(this.i)&&g.eb(this.l)};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.db(this.i,a)||g.db(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.nCa)(b,a);0<=c?(g.gb(b,c),b=!0):b=!1;return b||g.ib(this.l,a)};
g.k.sg=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Ra(A5,g.I);g.k=A5.prototype;g.k.mP=function(){this.If=Math.min(3E5,2*this.If);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.If+15E3*Math.random();g.kn(this.i,a);this.l=g.C()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.If=5E3};g.Ra(B5,hJa);g.k=B5.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Of=function(a){return this.u.Of(a)};
g.k.V=function(a,b){return this.u.V.apply(this.u,arguments)};
g.k.dispose=function(){this.X||(this.X=!0,g.Ni(this.u),lJa(this),g.Ni(this.l),this.l=null,this.Y=function(){return""})};
g.k.na=function(){return this.X};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.W="";this.l.stop();this.C=a||null;this.B=b||0;a=this.ca+"/test";b=this.ca+"/bind";var d=new t5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ea),e=this.i;e&&(e.yf=null);d.yf=this;this.i=d;C5(this);if(this.i){d=g.O("ID_TOKEN");var f=this.i.Ji||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Ji=f}e?(3!=e.getState()&&0==bJa(e)||e.getState(),this.i.connect(a,b,this.I,e.l,e.So)):c?this.i.connect(a,
b,this.I,c.sessionId,c.arrayId):this.i.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Tb(c,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.J.push(c):D5(this)&&(C5(this),aJa(this.i,c))};
g.k.IC=function(){this.l.reset();this.C=null;this.B=0;if(this.J.length){var a=this.J;this.J=[];for(var b=0,c=a.length;b<c;++b)aJa(this.i,a[b])}this.V("handlerOpened")};
g.k.GC=function(a){var b=2==a&&401==this.i.Ki;4==a||b||this.l.start();this.V("handlerError",a,b)};
g.k.ex=function(a){if(!this.l.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.J.push(d)}};
g.k.qD=function(){var a={v:2};this.W&&(a.gsessionid=this.W);0!=this.B&&(a.ui=""+this.B);0!=this.L&&(a.ui=""+this.L);this.C&&g.Tb(a,this.C);return a};
g.k.HC=function(a){"S"==a[0]?this.W=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),ZIa(this.i)):this.V("handlerMessage",new jJa(a[0],a[1]))};
g.k.Xu=function(a){(this.I.loungeIdToken=a)||this.l.stop();if(this.ia&&this.i){var b=this.i.Ji||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Ji=b}};
g.k.kQ=function(){this.l.isActive();0==bJa(this.i)&&this.connect(this.C,this.B)};E5.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
E5.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
E5.prototype.C=function(a){a(Error("request timed out"))};var sJa=g.C(),H5=null,K5=Array(50),J5=-1,L5=!1;g.Ra(M5,g.Q);M5.prototype.Pg=function(){return this.screens};
M5.prototype.contains=function(a){return!!H4(this.screens,a)};
M5.prototype.get=function(a){return a?I4(this.screens,a):null};
M5.prototype.info=function(a){I5(this.I,a)};g.u(N5,g.Q);g.k=N5.prototype;g.k.start=function(){!this.i&&isNaN(this.gb)&&this.dG()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.gb)||(g.Bo(this.gb),this.gb=NaN)};
g.k.da=function(){this.stop();g.Q.prototype.da.call(this)};
g.k.dG=function(){this.gb=NaN;this.i=g.Yp(F5(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.I},timeout:5E3,onSuccess:(0,g.B)(this.LJ,this),onError:(0,g.B)(this.KJ,this),onTimeout:(0,g.B)(this.MJ,this)})};
g.k.LJ=function(a,b){this.i=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new C4(c))};
g.k.KJ=function(a){this.i=null;a.status&&404==a.status?this.l>=IKa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=IKa[this.l],this.gb=g.zo((0,g.B)(this.dG,this),a),this.l++):this.V("pairingFailed",Error("Server error "+a.status))};
g.k.MJ=function(){this.i=null;this.V("pairingFailed",Error("Server not responding"))};
var IKa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ra(P5,M5);g.k=P5.prototype;g.k.start=function(){O5(this)&&this.V("screenChange");!g.Fu("yt-remote-lounge-token-expiration")&&wJa(this);g.Bo(this.i);this.i=g.zo((0,g.B)(this.start,this),1E4)};
g.k.add=function(a,b){O5(this);tJa(this,a);Q5(this,!1);this.V("screenChange");b(a);a.token||wJa(this)};
g.k.remove=function(a,b){var c=O5(this);vJa(this,a)&&(Q5(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.k.wv=function(a,b,c,d){var e=O5(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,Q5(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.k.da=function(){g.Bo(this.i);P5.Ed.da.call(this)};
g.k.wL=function(a){O5(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}Q5(this,!b);b&&I5(this.I,"Missed "+b+" lounge tokens.")};
g.k.vL=function(a){I5(this.I,"Requesting lounge tokens failed: "+a)};g.u(S5,g.Q);g.k=S5.prototype;g.k.start=function(){var a=parseInt(g.Fu("yt-remote-fast-check-period")||"0",10);(this.B=g.C()-144E5<a?0:a)?V5(this):(this.B=g.C()+3E5,g.Eu("yt-remote-fast-check-period",this.B),this.Gz())};
g.k.isEmpty=function(){return g.Mb(this.i)};
g.k.update=function(){R5("Updating availability on schedule.");var a=this.I(),b=g.Bb(this.i,function(c,d){return c&&!!I4(a,d)},this);
U5(this,b)};
g.k.da=function(){g.Bo(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.Q.prototype.da.call(this)};
g.k.Gz=function(){g.Bo(this.u);this.u=NaN;this.l&&this.l.abort();var a=yJa(this);if(y4(a)){var b=F5(this.C,"/pairing/get_screen_availability");this.l=G5(this.C,b,{lounge_token:g.Hb(a).join(",")},(0,g.B)(this.VO,this,a),(0,g.B)(this.UO,this))}else U5(this,{}),V5(this)};
g.k.VO=function(a,b){this.l=null;var c=g.Hb(yJa(this));if(g.wb(c,g.Hb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;U5(this,d);V5(this)}else this.Gd("Changing Screen set during request."),this.Gz()};
g.k.UO=function(a){this.Gd("Screen availability failed: "+a);this.l=null;V5(this)};
g.k.Gd=function(a){I5("OnlineScreenService",a)};g.Ra(W5,M5);g.k=W5.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.V("screenChange"),this.i.isEmpty()||this.V("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.wv=function(a,b,c,d){this.l.contains(a)?this.l.wv(a,b,c,d):(a="Updating name of unknown screen: "+a.name,I5(this.I,a),d(Error(a)))};
g.k.Pg=function(a){return a?this.screens:g.kb(this.screens,g.He(this.u,function(b){return!this.contains(b)},this))};
g.k.GB=function(){return g.He(this.Pg(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.HB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new N5(this.B,a,b,c);f.subscribe("pairingComplete",(0,g.B)(function(h){g.Ni(f);d(X5(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Ni(f);e(h)});
f.start();return(0,g.B)(f.stop,f)};
g.k.NJ=function(a,b,c,d){g.Yp(F5(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.B)(function(e,f){var h=new C4(f.screen||{});if(!h.name||CJa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);CJa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(X5(this,h))},this),
onError:(0,g.B)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.B)(function(){d(Error("pairing request timed out."))},this)})};
g.k.da=function(){g.Ni(this.l);g.Ni(this.i);W5.Ed.da.call(this)};
g.k.CL=function(){EJa(this);this.V("screenChange");this.i.update()};
W5.prototype.dispose=W5.prototype.dispose;g.Ra(Z5,g.Q);g.k=Z5.prototype;g.k.getScreen=function(){return this.u};
g.k.cg=function(a){this.na()||(a&&a6(this,""+a),this.u=null,this.V("sessionScreen",null))};
g.k.info=function(a){I5(this.ia,a)};
g.k.IB=function(){return null};
g.k.Rz=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.B)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.B)(function(){a6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.da=function(){this.Rz("");Z5.Ed.da.call(this)};g.u(b6,Z5);g.k=b6.prototype;g.k.Qz=function(a){if(this.l){if(this.l==a)return;a6(this,"Overriding cast session with new session object");MJa(this);this.ea=!1;this.W="unknown";this.l.removeUpdateListener(this.Y);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ca)}this.l=a;this.l.addUpdateListener(this.Y);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.ca);IJa(this,"getMdxSessionStatus")};
g.k.To=function(a){this.info("launchWithParams no-op for Cast: "+g.Oj(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.B)(function(){this.cg()},this),(0,g.B)(function(){this.cg(Error("Failed to stop receiver app."))},this)):this.cg(Error("Stopping cast device without session."))};
g.k.Rz=function(){};
g.k.da=function(){this.info("disposeInternal");MJa(this);this.l&&(this.l.removeUpdateListener(this.Y),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ca));this.l=null;Z5.prototype.da.call(this)};
g.k.HP=function(a,b){if(!this.na())if(b){var c=W4(b);if(g.Ma(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Oj(c));switch(d){case "mdxSessionStatus":GJa(this,c);break;case "loungeToken":JJa(this,c);break;default:a6(this,"Unknown youtube message: "+d)}}else a6(this,"Unable to parse message.")}else a6(this,"No data in message.")};
g.k.HD=function(a,b,c,d){g.Bo(this.L);this.L=0;BJa(this.B,this.i.label,a,this.i.friendlyName,(0,g.B)(function(e){e?b(e):0<=d?(a6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.L=g.zo((0,g.B)(this.HD,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.IB=function(){return this.l};
g.k.OJ=function(a){this.na()||a||(a6(this,"Cast session died."),this.cg())};g.u(e6,Z5);g.k=e6.prototype;g.k.Qz=function(a){this.C=a;this.C.addUpdateListener(this.X)};
g.k.To=function(a){this.Y=a;this.J()};
g.k.stop=function(){this.l();this.l=g.Ia;g.Bo(this.I);this.C?this.C.stop((0,g.B)(this.cg,this,null),(0,g.B)(this.cg,this,"Failed to stop DIAL device.")):this.cg()};
g.k.da=function(){this.l();this.l=g.Ia;g.Bo(this.I);this.C&&this.C.removeUpdateListener(this.X);this.C=null;Z5.prototype.da.call(this)};
g.k.PJ=function(a){this.na()||a||(a6(this,"DIAL session died."),this.l(),this.l=g.Ia,this.cg())};
g.k.wy=function(a){this.W=G4();if(this.Y){var b=new chrome.cast.DialLaunchResponse(!0,OJa(this));a(b);NJa(this)}else this.J=(0,g.B)(function(){g.Bo(this.I);this.J=g.Ia;this.I=NaN;var c=new chrome.cast.DialLaunchResponse(!0,OJa(this));a(c);NJa(this)},this),this.I=g.zo((0,g.B)(function(){this.J()},this),100)};
g.k.SL=function(a,b,c){BJa(this.B,this.L.receiver.label,a,this.i.friendlyName,(0,g.B)(function(d){d&&d.token?($5(this,d),b(new chrome.cast.DialLaunchResponse(!1))):this.wy(b,c)},this),(0,g.B)(function(d){a6(this,"Failed to get DIAL screen: "+d);
this.wy(b,c)},this))};g.u(f6,Z5);f6.prototype.stop=function(){this.cg()};
f6.prototype.Qz=function(){};
f6.prototype.To=function(){g.Bo(this.l);this.l=NaN;var a=I4(this.B.Pg(),this.i.label);a?$5(this,a):this.cg(Error("No such screen"))};
f6.prototype.da=function(){g.Bo(this.l);this.l=NaN;Z5.prototype.da.call(this)};g.u(g6,g.Q);g.k=g6.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.L);this.W||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.B)(this.FO,this);c=new chrome.cast.ApiConfig(c,(0,g.B)(this.MF,this),f,d,e);c.customDialLaunchCallback=(0,g.B)(this.sN,this);chrome.cast.initialize(c,(0,g.B)(function(){this.na()||
(chrome.cast.addReceiverActionListener(this.I),pJa(),this.l.subscribe("onlineScreenChange",(0,g.B)(this.JB,this)),this.u=QJa(this),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.B)(function(h){this.Gd("Failed to set initial custom receivers: "+g.Oj(h))},this)),this.V("yt-remote-cast2-availability-change",i6(this)),b(!0))},this),(0,g.B)(function(h){this.Gd("Failed to initialize API: "+g.Oj(h));
b(!1)},this))};
g.k.rQ=function(a,b){h6("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)h6("Unsetting old screen status: "+this.i.i.friendlyName),j6(this,null)}if(a&&b){if(!this.i){c=I4(this.l.Pg(),a);if(!c){h6("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){h6("setConnectedScreenStatus: Screen with id type to be short lived.");return}var d=PJa(this,c);d||(h6("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(d),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.B)(function(e){this.Gd("Failed to set initial custom receivers: "+g.Oj(e))},this)));
h6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);j6(this,new f6(this.l,d),!0)}this.i.Rz(b)}else h6("setConnectedScreenStatus: no screen.")};
g.k.sQ=function(a){this.na()?this.Gd("Setting connection data on disposed cast v2"):this.i?this.i.To(a):this.Gd("Setting connection data without a session")};
g.k.RJ=function(){this.na()?this.Gd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),j6(this,null)):h6("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.B)(this.MF,this),(0,g.B)(this.YO,this))};
g.k.da=function(){this.l.unsubscribe("onlineScreenChange",(0,g.B)(this.JB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.I);var a=mJa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.ib(b||[],a);g.Ni(this.i);g.Q.prototype.da.call(this)};
g.k.Gd=function(a){I5("Controller",a)};
g.k.OF=function(a,b){this.i==a&&(b||j6(this,null),this.V("yt-remote-cast2-session-change",b))};
g.k.CO=function(a,b){if(!this.na())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),h6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)h6("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{h6("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.V("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:j6(this,
new f6(this.l,a));break;case chrome.cast.ReceiverType.DIAL:j6(this,new e6(this.l,a,this.C));break;case chrome.cast.ReceiverType.CAST:j6(this,new b6(this.l,a,this.B));break;default:this.Gd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Gd("Stopping receiver w/o session: "+a.friendlyName)}else this.Gd("onReceiverAction_ called without receiver.")};
g.k.sN=function(a){if(this.na())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Gd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Gd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return h6("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Gd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);j6(this,new e6(this.l,b,this.C))}b=this.i;b.L=a;return b.L.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.B)(b.SL,b,(b.L.extraData||{}).screenId||null)):new Promise((0,g.B)(b.wy,b))};
g.k.MF=function(a){if(!this.na()){h6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(b.receiverType==chrome.cast.ReceiverType.CAST)h6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),j6(this,new b6(this.l,b,this.B),!0);else{this.Gd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.i.i,d=I4(this.l.Pg(),c.label);d&&D4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(h6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ni(this.i),this.i=new b6(this.l,b,this.B),this.i.subscribe("sessionScreen",(0,g.B)(this.OF,this,this.i)),this.i.To(null));this.i.Qz(a)}}};
g.k.QJ=function(){return this.i?this.i.IB():null};
g.k.YO=function(a){this.na()||(this.Gd("Failed to estabilish a session: "+g.Oj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&j6(this,null))};
g.k.FO=function(a){h6("Receiver availability updated: "+a);if(!this.na()){var b=i6(this);this.J=a==chrome.cast.ReceiverAvailability.AVAILABLE;i6(this)!=b&&this.V("yt-remote-cast2-availability-change",i6(this))}};
g.k.JB=function(){this.na()||(this.u=QJa(this),h6("Updating custom receivers: "+g.Oj(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.B)(function(){this.Gd("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",i6(this)))};
g6.prototype.setLaunchParams=g6.prototype.sQ;g6.prototype.setConnectedScreenStatus=g6.prototype.rQ;g6.prototype.stopSession=g6.prototype.RJ;g6.prototype.getCastSession=g6.prototype.QJ;g6.prototype.requestSession=g6.prototype.requestSession;g6.prototype.init=g6.prototype.init;g6.prototype.dispose=g6.prototype.dispose;var p6=[];g.k=u6.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";v6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.i=a.trackData,this.cj=a.hasPrevious,this.hasNext=a.hasNext,this.L=a.playerTime,this.J=a.playerTimeAt,this.C=a.seekableStart,this.l=a.seekableEnd,this.I=a.duration,this.W=a.loadedTime,this.B=a.liveIngestionTime,this.u=!isNaN(this.B))};
g.k.Kb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.u?this.I+w6(this):this.I};
g.k.clone=function(){return new u6(A6(this))};g.u(C6,g.Q);g.k=C6.prototype;g.k.getState=function(){return this.Ma};
g.k.play=function(){E6(this)?(this.i?this.i.play(null,g.Ia,J6(this,"play")):I6(this,"play"),H6(this,1,y6(D6(this))),this.V("remotePlayerChange")):F6(this,this.play)};
g.k.pause=function(){E6(this)?(this.i?this.i.pause(null,g.Ia,J6(this,"pause")):I6(this,"pause"),H6(this,2,y6(D6(this))),this.V("remotePlayerChange")):F6(this,this.pause)};
g.k.seekTo=function(a){if(E6(this)){if(this.i){var b=D6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Kb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,J6(this,"seekTo",{newTime:a}))}else I6(this,"seekTo",{newTime:a});H6(this,3,a);this.V("remotePlayerChange")}else F6(this,g.Pa(this.seekTo,a))};
g.k.stop=function(){if(E6(this)){this.i?this.i.stop(null,g.Ia,J6(this,"stopVideo")):I6(this,"stopVideo");var a=D6(this);a.index=-1;a.videoId="";v6(a);G6(this,a);this.V("remotePlayerChange")}else F6(this,this.stop)};
g.k.setVolume=function(a,b){if(E6(this)){var c=D6(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.B)(function(){I5("CP","set receiver volume: "+d)},this),(0,g.B)(function(){this.Gd("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.B)(function(){I5("CP","set receiver muted: "+b)},this),(0,g.B)(function(){this.Gd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);I6(this,"setVolume",e)}c.muted=b;c.volume=a;G6(this,c)}else F6(this,g.Pa(this.setVolume,a,b))};
g.k.KB=function(a,b){if(E6(this)){var c=D6(this),d={videoId:a};b&&(c.i={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Oj(b.style),g.Tb(d,c.i));I6(this,"setSubtitlesTrack",d);G6(this,c)}else F6(this,g.Pa(this.KB,a,b))};
g.k.setAudioTrack=function(a,b){if(E6(this)){var c=b.getLanguageInfo().getId();I6(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=D6(this);d.audioTrackId=c;G6(this,d)}else F6(this,g.Pa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=D6(this);c=c||0;var m={videoId:a,currentIndex:c};z6(l,a,c);void 0!==b&&(x6(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Oj(h));I6(this,"setPlaylist",m);d||G6(this,l)};
g.k.Ju=function(a,b){if(E6(this)){if(a&&b){var c=D6(this);z6(c,a,b);G6(this,c)}I6(this,"previous")}else F6(this,g.Pa(this.Ju,a,b))};
g.k.nextVideo=function(a,b){if(E6(this)){if(a&&b){var c=D6(this);z6(c,a,b);G6(this,c)}I6(this,"next")}else F6(this,g.Pa(this.nextVideo,a,b))};
g.k.aD=function(){E6(this)?I6(this,"dismissAutoplay"):F6(this,this.aD)};
g.k.dispose=function(){if(3!=this.Ma){var a=this.Ma;this.Ma=3;this.V("proxyStateChange",a,this.Ma)}g.Q.prototype.dispose.call(this)};
g.k.da=function(){bKa(this);this.u=null;this.B.clear();B6(this,null);g.Q.prototype.da.call(this)};
g.k.Uz=function(a){if((a!=this.Ma||2==a)&&3!=this.Ma&&0!=a){var b=this.Ma;this.Ma=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.eb(b.i)&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.zO=function(a,b){this.V(a,b)};
g.k.eN=function(a){if(!a)this.zr(null),B6(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=D6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)I5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,G6(this,b)}};
g.k.zr=function(a){I5("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.J);if(this.i=a)this.i.addUpdateListener(this.J),cKa(this),this.V("remotePlayerChange")};
g.k.dN=function(a){a?(cKa(this),this.V("remotePlayerChange")):this.zr(null)};
g.k.lA=function(){I6(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.lN=function(){var a=ZJa();a&&B6(this,a)};
g.k.Gd=function(a){I5("CP",a)};g.u(K6,g.Q);g.k=K6.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Fb.listId=c);this.Fb.videoId=d;this.Fb.index=h||0;this.Fb.state=3;x6(this.Fb,m);this.B="UNSUPPORTED";L6("Connecting with setPlaylist and params: "+g.Oj(l));this.i.connect({method:"setPlaylist",
params:g.Oj(l)},a,hIa())}else L6("Connecting without params"),this.i.connect({},a,hIa());eKa(this)};
g.k.Xu=function(a){this.i.Xu(a)};
g.k.dispose=function(){this.na()||(this.V("beforeDispose"),M6(this,3));g.Q.prototype.dispose.call(this)};
g.k.da=function(){N6(this);P6(this);O6(this);g.Bo(this.J);this.J=NaN;g.Bo(this.L);this.L=NaN;this.u=null;g.bp(this.W);this.W.length=0;this.i.dispose();g.Q.prototype.da.call(this);this.B=this.I=this.l=this.Fb=this.i=null};
g.k.qL=function(){this.uo(2)};
g.k.iN=function(){L6("Channel opened");this.ca&&(this.ca=!1,O6(this),this.Y=g.zo((0,g.B)(function(){L6("Timing out waiting for a screen.");this.uo(1)},this),15E3));
lIa(kJa(this.i),this.ga)};
g.k.fN=function(){L6("Channel closed");isNaN(this.C)?N4(!0):N4();this.dispose()};
g.k.gN=function(a,b){N4();isNaN(this.Vq())?(b&&"shortLived"==this.ea&&this.V("browserChannelAuthError",a),L6("Channel error: "+a+" without reconnection"),this.dispose()):(this.ca=!0,L6("Channel error: "+a+" with reconnection in "+this.Vq()+" ms"),M6(this,2))};
g.k.hN=function(a){a.params?L6("Received: action="+a.action+", params="+g.Oj(a.params)):L6("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=W4(a.params.devices);this.l=g.Jc(a,function(c){return new B4(c)});
a=!!g.$a(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
hKa(this,a);break;case "loungeScreenDisconnected":g.jb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
hKa(this,!1);break;case "remoteConnected":var b=new B4(W4(a.params.device));g.$a(this.l,function(c){return b?c.id==b.id:!1})||SHa(this.l,b);
break;case "remoteDisconnected":b=new B4(W4(a.params.device));g.jb(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":jKa(this,a);break;case "nowPlaying":lKa(this,a);break;case "onStateChange":kKa(this,a);break;case "onAdStateChange":mKa(this,a);break;case "onVolumeChanged":nKa(this,a);break;case "onSubtitlesTrackChanged":iKa(this,a);break;case "nowAutoplaying":oKa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.V("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.V("autoplayModeChange",this.B);"DISABLED"==this.B&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":pKa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:L6("Unrecognized action: "+a.action)}};
g.k.gQ=function(){if(this.u){var a=this.u;this.u=null;this.Fb.videoId!=a&&Q6(this,"getNowPlaying")}};
g.k.mL=function(){var a=3;this.na()||(a=0,isNaN(this.Vq())?D5(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.uo=function(a){L6("Disconnecting with "+a);N6(this);this.V("beforeDisconnect",a);1==a&&N4();lJa(this.i,a);this.dispose()};
g.k.kL=function(){var a=this.Fb;this.u&&(a=this.Fb.clone(),z6(a,this.u,a.index));return A6(a)};
g.k.tQ=function(a){var b=new u6(a);b.videoId&&b.videoId!=this.Fb.videoId&&(this.u=b.videoId,g.Bo(this.J),this.J=g.zo((0,g.B)(this.gQ,this),5E3));var c=[];this.Fb.listId==b.listId&&this.Fb.videoId==b.videoId&&this.Fb.index==b.index||c.push("remoteQueueChange");this.Fb.playerState==b.playerState&&this.Fb.volume==b.volume&&this.Fb.muted==b.muted&&y6(this.Fb)==y6(b)&&g.Oj(this.Fb.i)==g.Oj(b.i)||c.push("remotePlayerChange");this.Fb.reset(a);g.yb(c,function(d){this.V(d)},this)};
g.k.GD=function(){var a=this.i.I.id,b=g.$a(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Vq=function(){var a=this.i;return a.l.isActive()?a.l.l-g.C():NaN};
g.k.gL=function(){return this.B||"UNSUPPORTED"};
g.k.hL=function(){return this.I||""};
g.k.SJ=function(){if(!isNaN(this.Vq())){var a=this.i.l;a.i.Og();a.start()}};
g.k.pQ=function(a,b){Q6(this,a,b);gKa(this)};
g.k.LB=function(){var a=g.Sq("SID","")||"",b=g.Sq("SAPISID","")||"",c=g.Sq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.of(g.Re(a),2);b=g.of(g.Re(b),2);c=g.of(g.Re(c),2);return g.of(g.Re(a+","+b+","+c),2)};
K6.prototype.subscribe=K6.prototype.subscribe;K6.prototype.unsubscribeByKey=K6.prototype.Of;K6.prototype.getProxyState=K6.prototype.mL;K6.prototype.disconnect=K6.prototype.uo;K6.prototype.getPlayerContextData=K6.prototype.kL;K6.prototype.setPlayerContextData=K6.prototype.tQ;K6.prototype.getOtherConnectedRemoteId=K6.prototype.GD;K6.prototype.getReconnectTimeout=K6.prototype.Vq;K6.prototype.getAutoplayMode=K6.prototype.gL;K6.prototype.getAutoplayVideoId=K6.prototype.hL;K6.prototype.reconnect=K6.prototype.SJ;
K6.prototype.sendMessage=K6.prototype.pQ;K6.prototype.getXsrfToken=K6.prototype.LB;g.u(R6,M5);g.k=R6.prototype;g.k.Pg=function(a){return this.Hf.$_gs(a)};
g.k.contains=function(a){return!!this.Hf.$_c(a)};
g.k.get=function(a){return this.Hf.$_g(a)};
g.k.start=function(){this.Hf.$_st()};
g.k.add=function(a,b,c){this.Hf.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Hf.$_r(a,b,c)};
g.k.wv=function(a,b,c,d){this.Hf.$_un(a,b,c,d)};
g.k.da=function(){for(var a=0,b=this.i.length;a<b;++a)this.Hf.$_ubk(this.i[a]);this.i.length=0;this.Hf=null;M5.prototype.da.call(this)};
g.k.TJ=function(){this.V("screenChange")};
g.k.gO=function(){this.V("onlineScreenChange")};
W5.prototype.$_st=W5.prototype.start;W5.prototype.$_gspc=W5.prototype.NJ;W5.prototype.$_gsppc=W5.prototype.HB;W5.prototype.$_c=W5.prototype.contains;W5.prototype.$_g=W5.prototype.get;W5.prototype.$_a=W5.prototype.add;W5.prototype.$_un=W5.prototype.wv;W5.prototype.$_r=W5.prototype.remove;W5.prototype.$_gs=W5.prototype.Pg;W5.prototype.$_gos=W5.prototype.GB;W5.prototype.$_s=W5.prototype.subscribe;W5.prototype.$_ubk=W5.prototype.Of;var d7=null,j7=!1,S6=null,T6=null,i7=null,X6=[];g.u(k7,g.I);g.k=k7.prototype;g.k.da=function(){g.I.prototype.da.call(this);this.i.stop();this.u.stop();this.L.stop();this.Y();var a=this.wb;a.unsubscribe("proxyStateChange",this.JF,this);a.unsubscribe("remotePlayerChange",this.Fr,this);a.unsubscribe("remoteQueueChange",this.Gu,this);a.unsubscribe("previousNextChange",this.GF,this);a.unsubscribe("nowAutoplaying",this.BF,this);a.unsubscribe("autoplayDismissed",this.bF,this);this.wb=this.l=null};
g.k.MB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.wb.Ma)if(l7(this)){if(!D6(this.wb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":D6(this.wb).Kb()?this.wb.pause():this.wb.play();break;case "control_play":this.wb.play();break;case "control_pause":this.wb.pause();break;case "control_seek":this.J.Og(c[0],c[1]);break;case "control_subtitles_set_track":m7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.G.getCurrentTime();n7(this,0===c?void 0:c);break;case "control_seek":n7(this,c[0]);break;case "control_subtitles_set_track":m7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.bN=function(a){this.L.Og(a)};
g.k.ZQ=function(a){this.MB("control_subtitles_set_track",g.Mb(a)?null:a)};
g.k.ZG=function(){var a=this.G.getOption("captions","track");g.Mb(a)||m7(this,a)};
g.k.Bb=function(a){this.l.Bb(a,this.G.getVideoData().lengthSeconds)};
g.k.PN=function(){g.Mb(this.B)||AKa(this,this.B);this.C=!1};
g.k.JF=function(a,b){this.u.stop();2===b&&this.UG()};
g.k.Fr=function(){if(l7(this)){this.i.stop();var a=D6(this.wb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.Ne=1;break;case 1082:case 1083:this.l.Ne=0;break;default:this.l.Ne=-1}switch(a.playerState){case 1081:case 1:this.tb(new g.uK(8));this.TG();break;case 1085:case 3:this.tb(new g.uK(9));break;case 1083:case 0:this.tb(new g.uK(2));this.J.stop();this.Bb(this.G.getVideoData().lengthSeconds);break;case 1084:this.tb(new g.uK(4));break;case 2:this.tb(new g.uK(4));this.Bb(y6(a));
break;case -1:this.tb(new g.uK(64));break;case -1E3:this.tb(new g.uK(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=D6(this.wb).i;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,AKa(this,a));a=D6(this.wb);-1===a.volume||Math.round(this.G.getVolume())===a.volume&&this.G.isMuted()===a.muted||this.W.isActive()||this.wH()}else zKa(this)};
g.k.GF=function(){this.G.V("mdxpreviousnextchange")};
g.k.Gu=function(){l7(this)||zKa(this)};
g.k.BF=function(a){isNaN(a)||this.G.V("mdxnowautoplaying",a)};
g.k.bF=function(){this.G.V("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){l7(this)&&this.wb.setAudioTrack(this.G.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===D6(this.wb).playerState?n7(this,a):b&&this.wb.seekTo(a)};
g.k.wH=function(){var a=this;if(l7(this)){var b=D6(this.wb);this.events.Gb(this.X);b.muted?this.G.mute():this.G.unMute();this.G.setVolume(b.volume);this.X=this.events.N(this.G,"onVolumeChange",function(c){yKa(a,c)})}};
g.k.TG=function(){this.i.stop();if(!this.wb.na()){var a=D6(this.wb);a.Kb()&&this.tb(new g.uK(8));this.Bb(y6(a));this.i.start()}};
g.k.UG=function(){this.u.stop();this.i.stop();var a=this.wb.u.getReconnectTimeout();2==this.wb.Ma&&!isNaN(a)&&this.u.start()};
g.k.tb=function(a){this.u.stop();var b=this.I;if(!g.zK(b,a)){var c=g.V(a,2);c!==g.V(this.I,2)&&this.G.Bn(c);this.I=a;CKa(this.l,b,a)}};g.u(o7,g.W);o7.prototype.Ec=function(){this.i.show()};
o7.prototype.jb=function(){this.i.hide()};
o7.prototype.l=function(){g.aK("https://support.google.com/youtube/answer/7640706")};
o7.prototype.u=function(){A4("mdx-manual-pairing-popup-ok");this.jb()};g.u(p7,g.W);p7.prototype.Ec=function(){this.i.show()};
p7.prototype.jb=function(){this.i.hide()};
p7.prototype.l=function(){A4("mdx-privacy-popup-cancel");this.jb()};
p7.prototype.u=function(){A4("mdx-privacy-popup-confirm");this.jb()};g.u(q7,g.W);q7.prototype.l=function(a){BKa(this,a.state)};g.u(r7,g.SQ);r7.prototype.C=function(){var a=this.G.getOption("remote","receivers");a&&1<a.length&&!this.G.getOption("remote","quickCast")?(this.Ml=g.zb(a,this.i,this),g.TQ(this,g.Jc(a,this.i)),a=this.G.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.fh(a),this.enable(!0)):this.enable(!1)};
r7.prototype.i=function(a){return a.key};
r7.prototype.Nh=function(a){return"cast-selector-receiver"===a?"Cast...":this.Ml[a].name};
r7.prototype.Te=function(a){g.SQ.prototype.Te.call(this,a);this.G.setOption("remote","currentReceiver",this.Ml[a]);this.bb.jb()};g.u(s7,g.GN);g.k=s7.prototype;
g.k.create=function(){var a=this.player.T(),b=g.TC(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.S(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.S(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.S(a.experiments,"enable_cast_short_lived_lounge_token")};tKa(b,a);this.subscriptions.push(g.Go("yt-remote-before-disconnect",this.ZM,this));this.subscriptions.push(g.Go("yt-remote-connection-change",this.GO,this));this.subscriptions.push(g.Go("yt-remote-receiver-availability-change",
this.IF,this));this.subscriptions.push(g.Go("yt-remote-auto-connect",this.EO,this));this.subscriptions.push(g.Go("yt-remote-receiver-resumed",this.DO,this));this.subscriptions.push(g.Go("mdx-privacy-popup-confirm",this.WP,this));this.subscriptions.push(g.Go("mdx-privacy-popup-cancel",this.VP,this));this.subscriptions.push(g.Go("mdx-manual-pairing-popup-ok",this.hM,this));this.IF()};
g.k.load=function(){this.player.cancelPlayback();g.GN.prototype.load.call(this);this.lh=new k7(this,this.player,this.wb);var a=(a=xKa())?a.currentTime:0;var b=h7()?new C6(b7(),void 0):null;0==a&&b&&(a=y6(D6(b)));0!==a&&this.Bb(a);CKa(this,this.Mc,this.Mc);this.player.Dj(6)};
g.k.unload=function(){this.player.V("mdxautoplaycanceled");this.al=this.gi;g.Oi(this.lh,this.wb);this.wb=this.lh=null;g.GN.prototype.unload.call(this);this.player.Dj(5);t7(this)};
g.k.da=function(){g.Ho(this.subscriptions);g.GN.prototype.da.call(this)};
g.k.tj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.lh.MB.apply(this.lh,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.Ne};
g.k.nL=function(){return this.loaded?this.lh.suggestion:null};
g.k.cj=function(){return this.wb?D6(this.wb).cj:!1};
g.k.hasNext=function(){return this.wb?D6(this.wb).hasNext:!1};
g.k.Bb=function(a,b){this.vE=a||0;this.player.V("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.vE};
g.k.getProgressState=function(){var a=D6(this.wb),b=this.player.getVideoData();return{allowSeeking:g.S(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Le():!a.isAdPlaying()&&this.player.Le(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+w6(a):a.B,isAtLiveHead:1>=(a.u?a.l+w6(a):a.l)-this.getCurrentTime(),loaded:a.W,seekableEnd:a.u?a.l+w6(a):a.l,seekableStart:0<a.C?a.C+
w6(a):a.C}};
g.k.nextVideo=function(){this.wb&&this.wb.nextVideo()};
g.k.Ju=function(){this.wb&&this.wb.Ju()};
g.k.ZM=function(a){1===a&&(this.vz=this.wb?D6(this.wb):null)};
g.k.GO=function(){var a=h7()?new C6(b7(),void 0):null;if(a){var b=this.al;this.loaded&&this.unload();this.wb=a;this.vz=null;b.key!==this.gi.key&&(this.al=b,this.load())}else g.Ni(this.wb),this.wb=null,this.loaded&&(this.unload(),(a=this.vz)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,y6(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.IF=function(){var a=[this.gi],b=a.concat,c=uKa();q6()&&g.Fu("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Ml=b.call(a,c);a=c7()||this.gi;u7(this,a);this.player.xa("onMdxReceiversChange")};
g.k.EO=function(){var a=c7();u7(this,a)};
g.k.DO=function(){this.al=c7()};
g.k.WP=function(){this.Ir=!0;t7(this);j7=!1;d7&&f7(d7,1);d7=null};
g.k.VP=function(){this.Ir=!1;t7(this);u7(this,this.gi);this.al=this.gi;j7=!1;d7=null;this.player.playVideo()};
g.k.hM=function(){this.lu=!0;t7(this);g.Eu("yt-remote-manual-pairing-warning-shown",!0,2592E3);j7=!1;d7&&f7(d7,1);d7=null};
g.k.Ge=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Ml;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?s6():u7(this,b)),this.loaded?this.al:this.gi;case "quickCast":return 2===this.Ml.length&&"cast-selector-receiver"===this.Ml[1].key?(b&&s6(),!0):!1}};
g.k.lA=function(){this.wb.lA()};
g.k.xi=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.MN.remote=s7;})(_yt_player);
